(() => {
 'use strict';
 const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const base=window.ARUZ_DATA, E=window.AruzEngine;
 let corpus={}, lessons=[], lessonSources=[], recordings={}, archiveFixes={}, allLines=[];
 const siteBase=new URL('.',location.href);
 const siteLink=(params,hash)=>{const url=new URL(siteBase);url.search=new URLSearchParams(params).toString();url.hash=hash;return url.href};
 const KEY='failatun-learning-v4';
 let loaded={};try{loaded=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{}
 let legacy={};try{legacy=JSON.parse(localStorage.getItem('failatun-meclis-v3')||'{}')||{}}catch{}
 const state={chapter:loaded.chapter||legacy.chapter||'muhibbi',panel:loaded.panel||'anlam',level:['baslangic','orta','ileri'].includes(loaded.level)?loaded.level:'baslangic',lesson:loaded.lesson||null,completed:Array.isArray(loaded.completed)?loaded.completed:[],answers:loaded.answers&&typeof loaded.answers==='object'?loaded.answers:{},bookmarks:Array.isArray(loaded.bookmarks)?loaded.bookmarks:Array.isArray(legacy.bookmarks)?legacy.bookmarks:[],mistakes:Array.isArray(loaded.mistakes)?loaded.mistakes:[],journeys:loaded.journeys&&typeof loaded.journeys==='object'&&!Array.isArray(loaded.journeys)?loaded.journeys:{},lastJourney:loaded.lastJourney||null};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{} updateProgress()};
 function updateProgress(){const n=state.completed.length;$('#headerProgress').textContent=n?`${n} / ${lessons.length||12} ders ↗`:'Öğrenmeye başla ↗'}
 let toastTimer;
 function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
 function showDialog(html){$('#dialogContent').innerHTML=html;$('#infoDialog').showModal()}
 $('#closeDialog').onclick=()=>$('#infoDialog').close();$('#infoDialog').addEventListener('click',e=>{if(e.target===$('#infoDialog'))$('#infoDialog').close()});
 function sourceLinks(ids){return [...new Set(ids||[])].map(id=>{const s=corpus.sources?.[id]||lessonSources.find(s=>s.id===id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`:''}).filter(Boolean).join('<br>')}
 $('#aboutButton').onclick=()=>showDialog(`<h2>Sözün izi belli olsun.</h2><p>Fâilâtün, Hayâtî İnanç'ın şiir meclislerinden ilham alan bağımsız bir ders çalışmasıdır. Hocanın sesi yalnız asıl kayıtlarından dinletilir; ses klonlanmaz.</p><p>Metinler ve kalıplar aşağıdaki kaynaklarla desteklenir. Hece hece taktîler, kaynak metinler esas alınarak Fâilâtün için hazırlanmıştır. Serbest mısra incelemesi bir ön çalışmadır.</p><p>Ders ilerlemen ve defterin bu tarayıcıda saklanır; cihazlar arasında eşitlenmez. Kayıtları oynatırken YouTube'a bağlanılır. Beyit zamanları otomatik altyazıdan çıkarılmış yaklaşık aralıklardır; asıl kaydın tamamını da açabilirsin.</p><ul>${Object.values(corpus.sources||{}).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a></li>`).join('')}<li><a href="https://hayatiinanc.com/biyografi/" target="_blank" rel="noopener">Hayâtî İnanç · Resmî biyografi</a></li></ul>`);
 let meclisMode='guided';let ready=false,route='kesfet',scanPrefill='',scanTokens=null,scanText='';
 const getChapter=()=>base.chapters.find(c=>c.id===state.chapter)||base.chapters[0];
 const intro=(k,t,d)=>`<div class="page-intro"><div><span class="eyebrow">${k}</span><h1>${t}</h1></div><p class="intro-copy">${d}</p></div>`;
 function chapterLines(id){return id==='fuzuli'?(corpus.recordingAlternatives?.fuzuli?.lines||[]):(corpus.lines||[]).filter(l=>l.id.startsWith(id+'-'))}
 function chapterData(c){const alt=c.id==='fuzuli'?corpus.recordingAlternatives?.fuzuli:null;return {...c,...(alt?{meaning:alt.meaning,deep:alt.deep,prompts:alt.prompts,theme:'Su Kasidesi · aşk · iştiyak'}:{}),lines:chapterLines(c.id).length?chapterLines(c.id).map(l=>l.text):c.lines}}
 const WORDS={muhibbi:[['Mu‘teber','Değer verilen, itibarlı.'],['Devlet','Makam ve iktidar; aynı zamanda talih, saadet. Beyitteki mana inceliklerini birlikte düşün.'],['Cihân','Dünya, âlem.'],['Sıhhat','Sağlık; beden ve ruh bakımından afiyet.']],fuzuli:[['Leb','Dudak. Naatta hitap edilen sevgili için düşünülür.'],['Müştâk','Hasret çeken, kavuşmayı çok isteyen.'],['Zühhâd','Zâhidler; dünya zevklerinden uzak duranlar.'],['Kevser','Cennetteki su, havuz veya ırmak.'],['Mest / hûşyâr','Sarhoş / ayık. Şiirde aşk ve idrak tezadını kurar.'],['Mey','Şarap; bu şiirde mecaz katmanıyla okunur.']],galib:[['Zât','Kişinin kendisi, özü.'],['Zübde','Öz, en seçkin parça.'],['Merdüm-i dîde','Göz bebeği. “Merdüm” insan manasını da taşır.'],['Ekvân','Varlıklar, oluşlar; kâinat.']],nabi:[['Edeb','Hürmetli, ölçülü ve yerinde davranma.'],['Kûy','Semt, mahalle, belde.'],['Mahbûb-ı Hudâ','Allah’ın sevgilisi.'],['Nazargâh','Bakışın yöneldiği yer.']],hayali:[['Cihân-ârâ','Dünyayı süsleyen.'],['Ârâ','Süsleyici, bezeyici; “cihân-ârâ” terkibine bağlanır.'],['Mâhî','Balık.'],['Deryâ','Deniz.']],yahya:[['Handân','Gülen, sevinçli.'],['Visâl','Kavuşma.'],['Firkat','Ayrılık.'],['Kemâl / zevâl','Olgunluğa veya son sınıra erişme / sona erme, yok olma.']]};
 function normalizeNotebook(data){
  const raw=data.learning||{},chapterIds=base.chapters.map(c=>c.id),bookIds=[...chapterIds,...base.records.map(r=>r.id)],answers={},completed=[],mistakes=[];
  lessons.forEach(l=>{l.questions.forEach((q,i)=>{const id=l.id+':'+i,a=raw.answers?.[id];if(Number.isInteger(a)&&a>=0&&a<q.choices.length){answers[id]=a;if(a!==q.answer)mistakes.push({id,lesson:l.id,question:i})}});if(l.questions.every((q,i)=>answers[l.id+':'+i]===q.answer))completed.push(l.id)});
  const journeys={};chapterIds.forEach(id=>{if(raw.journeys?.[id])journeys[id]=window.AruzJourney.restore(raw.journeys[id],window.AruzJourney.lessonFor(base.chapters.find(c=>c.id===id),chapterLines(id)))});
  const lesson=lessons.find(l=>l.id===raw.lesson),learning={chapter:chapterIds.includes(raw.chapter)?raw.chapter:'muhibbi',panel:['anlam','takti','kelimeler'].includes(raw.panel)?raw.panel:'anlam',level:lesson?.level||(['baslangic','orta','ileri'].includes(raw.level)?raw.level:'baslangic'),lesson:lesson?.id||null,answers,completed,mistakes,bookmarks:[...new Set(Array.isArray(raw.bookmarks)?raw.bookmarks.filter(id=>bookIds.includes(id)):[])],journeys,lastJourney:chapterIds.includes(raw.lastJourney)?raw.lastJourney:null};
  const plans=window.AruzPlay.makePlans(base.chapters.map(chapterData),chapterLines),play=window.AruzPlay.restore(data.play,plans);
  return {learning,play};
 }
 $('#notebookButton').onclick=()=>{if(!ready){toast('Meclis yüklenince defterini açabilirsin.');return}window.AruzNotebook.open({showDialog,snapshot:()=>normalizeNotebook({learning:state,play:window.AruzPlay.snapshot()}),normalize:normalizeNotebook,toast,onApply:data=>{stopMedia();Object.assign(state,data.learning);window.AruzPlay.replaceProgress(data.play);const url=new URL(location.href);url.search='';history.replaceState(null,'',url);render();updateProgress()}})};
 function toggleBookmark(id){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];save();toast(state.bookmarks.includes(id)?'Defterine eklendi.':'Defterinden çıkarıldı.')}
 function renderMeclis(){if(meclisMode==='guided'&&!document.body.classList.contains('projector')){renderJourney();return}const raw=getChapter(),c=chapterData(raw);
  $('#main').innerHTML=intro('BEYİTLER','Hayâtî İnanç’tan dinle.','Bir beytin kelimelerini, manasını ve veznini aynı yerde aç. Takıldığın heceye dokun; sebebini gör.')+`<div class="listen-links"><a href="#ritimler">▶ Kalıpların ritmini dinle</a><a href="#arsiv">Kayıtların tamamı ↗</a><button class="text-button" id="guidedExplore">Birlikte çalış →</button></div><div class="workspace"><aside><div class="chapter-list" aria-label="Şiir seç">${base.chapters.map(ch=>`<button class="chapter-button ${ch.id===c.id?'active':''}" data-chapter="${ch.id}" aria-pressed="${ch.id===c.id}"><span class="n">${ch.number}</span><span><strong>${esc(ch.poet)}</strong><small>${esc(ch.theme.split(' · ')[0])}</small></span></button>`).join('')}</div><p class="sidebar-note">Uzun hece <b>—</b><br>Kısa hece <b>⏑</b><br><br>Tef‘ile çizgisi, mutlaka susulacak yer demek değildir.</p></aside><section><article class="poem-card"><div class="poem-topline"><span class="series">${esc(c.series)}</span><button class="bookmark" id="chapterSave" aria-label="Beyti defterine ekle" aria-pressed="${state.bookmarks.includes(c.id)}">${state.bookmarks.includes(c.id)?'★':'☆'}</button></div><div class="poem-stage"><div class="poet-name">${esc(c.poet.toLocaleUpperCase('tr-TR'))}</div><div class="couplet">${c.lines.map((l,i)=>`<div class="poem-line" data-poem-line="${i}">${esc(l)}</div>`).join('')}</div><div class="poem-theme">${esc(c.theme)}</div></div><div class="record-player" id="recordPlayer"></div><div class="reading-tools" role="tablist" aria-label="Beyti keşfet">${[['anlam','Mana'],['takti','Hece ve ritim'],['kelimeler','Kelimeler']].map(([key,title])=>`<button role="tab" id="tab-${key}" aria-controls="readingPanel" aria-selected="${state.panel===key}" tabindex="${state.panel===key?0:-1}" class="${state.panel===key?'active':''}" data-panel="${key}">${title}</button>`).join('')}</div><div class="reading-panel" id="readingPanel" role="tabpanel" aria-labelledby="tab-${state.panel}"></div></article><div class="under-stage"><span>Arûza yeni mi başlıyorsun?</span><a href="#dersler">İlk derste açık ve kapalı heceyi tanı →</a></div></section></div>`;
  $('#guidedExplore').onclick=()=>{stopMedia();meclisMode='guided';renderMeclis()};
  $$('[data-chapter]').forEach(b=>b.onclick=()=>{stopMedia();state.chapter=b.dataset.chapter;save();renderMeclis()});
  $$('[data-panel]').forEach((b,i,buttons)=>{b.onclick=()=>{state.panel=b.dataset.panel;save();buttons.forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b);x.tabIndex=x===b?0:-1});$('#readingPanel').setAttribute('aria-labelledby',b.id);renderReading()};b.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=buttons[(i+(e.key==='ArrowRight'?1:buttons.length-1))%buttons.length];next.click();next.focus()}}});
  $('#chapterSave').onclick=()=>{toggleBookmark(c.id);$('#chapterSave').textContent=state.bookmarks.includes(c.id)?'★':'☆';$('#chapterSave').setAttribute('aria-pressed',state.bookmarks.includes(c.id))};renderPlayer(c);renderReading();
 }
 function completedJourneys(){return base.chapters.filter(ch=>{const ls=chapterLines(ch.id),lesson=window.AruzJourney.lessonFor(ch,ls);return window.AruzJourney.isComplete(window.AruzJourney.restore(state.journeys[ch.id],lesson),lesson)}).map(ch=>ch.id)}
 function renderJourney(){const c=chapterData(getChapter());window.AruzJourney.render({chapter:c,chapters:base.chapters,lines:chapterLines(c.id),words:WORDS[c.id]||[],progress:state.journeys[c.id],completedIds:completedJourneys(),esc,marks:E.marks,renderPlayer,playPattern,stopTones,sourceLinks,isSaved:state.bookmarks.includes(c.id),onSave:()=>toggleBookmark(c.id),onUpdate:p=>{state.journeys[c.id]=p;state.lastJourney=c.id;save()},onChapter:id=>{stopMedia();state.chapter=id;save();renderMeclis()},onFree:()=>{stopMedia();meclisMode='free';renderMeclis()}})}
 function renderStudyReturn(){const ch=base.chapters.find(ch=>ch.id===state.lastJourney);if(!ch||!state.journeys[ch.id])return;const lesson=window.AruzJourney.lessonFor(ch,chapterLines(ch.id)),progress=window.AruzJourney.restore(state.journeys[ch.id],lesson);if(!progress.step&&!progress.meaning&&!progress.checked)return;const box=document.createElement('div');box.className='study-return';box.innerHTML=`<div><strong>${esc(ch.poet)} atölyesi</strong><span>${window.AruzJourney.isComplete(progress,lesson)?'Üç tatbikatı tamamladın. Yeni bir beyte geçebilirsin.':`${['Dinle','Anla','Ritmi izle','Kendin çöz'][progress.step]} adımında kaldın.`}</span></div><a href="#meclis" id="resumeJourney">${window.AruzJourney.isComplete(progress,lesson)?'Atölyeye dön':'Kaldığın yerden devam et'} →</a>`;$('.brand-home').prepend(box);$('#resumeJourney').onclick=()=>{state.chapter=ch.id;meclisMode='guided';save()}}
 function scanMarkup(line){let index=0;return `<p class="scan-line-label">${esc(line.text)}</p><div class="feet-row">${line.feet.map(f=>`<div class="foot"><div class="foot-syllables">${f.syllables.map(s=>`<button class="syllable ${s.mark==='S'?'short':''} ${s.operation?'operation':''}" data-syllable="${index++}" data-line="${esc(line.id)}" aria-label="${esc(s.text)}: ${s.mark==='LS'?'med, uzun ve kısa':s.mark==='S'?'kısa':'uzun'}. İzahı aç."><span>${esc(s.text)}</span><span class="marks">${E.marks(s.mark)}</span></button>`).join('')}</div><span class="foot-name">${esc(f.name)}</span></div>`).join('')}</div>`}
 function bindSyllables(container){$$('[data-syllable]',container).forEach(b=>b.onclick=()=>{const l=allLines.find(x=>x.id===b.dataset.line),s=l?.feet.flatMap(f=>f.syllables)[Number(b.dataset.syllable)];if(!s)return;$$('[data-syllable]',container).forEach(x=>x.classList.toggle('selected',x===b));const op={imale:'İmâle',med:'Med',line_end:'Mısra sonu',vasl:'Vasl'}[s.operation];const note=s.note||(s.operation==='imale'?'Bu açık hece, kalıptaki uzun konumu karşılamak için uzatılır.':s.operation==='line_end'?'Mısra sonundaki açık hece uzun kabul edilir; bu imâle olarak sayılmaz.':s.natural==='S'?'Kısa sesli harfle biten açık hece, burada kısa konumu karşılar.':'Kapalı veya aslî uzun sesli taşıyan bu hece, uzun konumu karşılar.');const target=$('.operation-detail',container);if(target){target.innerHTML=`<b>${esc(s.text)} · ${esc(op||'Hece değeri')}</b><br>${esc(note)}`;target.setAttribute('aria-live','polite')}})}
 function renderReading(){const c=chapterData(getChapter()),lines=chapterLines(c.id);
  if(state.panel==='anlam'){$('#readingPanel').innerHTML=`<span class="mini-label">BEYTİN MANASI</span><p class="meaning">${esc(c.meaning)}</p><p class="meaning-detail">${esc(c.deep)}</p><div class="action-row"><button class="text-button" id="speakMeaning">◖ İzahı cihaz sesiyle dinle</button></div><div class="note-box"><b>Dinlerken yakala</b><br>${c.prompts.map(esc).join(' · ')}</div>`;$('#speakMeaning').onclick=()=>{if(!window.speechSynthesis){toast('Bu cihaz sesli izahı desteklemiyor.');return}if(window.speechSynthesis.speaking){window.speechSynthesis.cancel();return}const u=new SpeechSynthesisUtterance(c.meaning);u.lang='tr-TR';u.rate=.9;const v=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('tr'));if(v)u.voice=v;window.speechSynthesis.speak(u)}}
  else if(state.panel==='kelimeler')$('#readingPanel').innerHTML=`<div class="dictionary">${(WORDS[c.id]||[]).map(([w,m])=>`<div class="word-card"><b>${esc(w)}</b><p>${esc(m)}</p></div>`).join('')}</div><p class="subtle" style="margin-top:18px">Kelimelerin burada verilen manaları, bu beyitteki kullanılışlarına göredir.</p>`;
  else {const ids=lines.flatMap(l=>l.sourceIds||[]);$('#readingPanel').innerHTML=`<div class="meter-title"><h3>${esc(lines[0]?.meterRealization||c.meter)}</h3><span class="badge verified">Metin ve kalıp kaynaklı</span></div><div class="legend"><span><b>—</b> Uzun</span><span><b>⏑</b> Kısa</span><span><b>— ⏑</b> Tek hecede med</span></div>${lines.map(scanMarkup).join('')}<div class="note-box operation-detail"><b>Bir hece seç</b><br>Altın zeminli hecelerde imâle, med veya mısra sonu izahı var.</div>${lines.map(l=>(l.notes||[]).map(n=>`<p class="subtle" style="margin-top:12px">${esc(n)}</p>`).join('')).join('')}<div class="action-row"><button class="secondary" id="playMeter">◖ Kalıbın ritmini dinle</button><button class="text-button" id="toScanner">İlk mısrayı laboratuvarda aç →</button></div><p class="subtle" style="margin-top:14px">Bu taktî Fâilâtün için hazırlanmıştır. Metindeki ve telaffuzdaki farklar başka okuyuşlara da imkân verebilir.</p><details class="source-list"><summary>Metin ve vezin kaynakları</summary>${sourceLinks(ids)}</details>`;bindSyllables($('#readingPanel'));$('#playMeter').onclick=()=>playPattern(lines[0]?.pattern||c.pattern);$('#toScanner').onclick=()=>{scanPrefill=lines[0]?.text||c.lines[0];location.hash='laboratuvar'}}
 }
 // The original recording stays in the visible YouTube player; controls use its official API.
 let ytPromise,ytPlayer=null,playerTimer=null,playerEpoch=0,clipLoop=false,slow=false,audioIntent=null;
 function loadYT(){if(window.YT?.Player)return Promise.resolve();if(ytPromise)return ytPromise;ytPromise=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{ytPromise=null;reject(new Error('player unavailable'))},12000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timer);resolve()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{clearTimeout(timer);ytPromise=null;reject(new Error('player unavailable'))};document.head.append(s)});return ytPromise}
 const time=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
 function renderPlayer(c){const clip=recordings[c.id],start=clip?.playbackStartSec||0,end=(clip?.endSec||30)+.2;
  $('#recordPlayer').innerHTML=`<div class="player-head"><button class="play-button" id="clipPlay" aria-label="Beyti asıl kayıttan dinle">▶</button><div class="player-title"><button class="record-name-button" id="recordName">▶ Hayâtî İnanç’tan dinle</button><small>Asıl kayıt · ${clip?`${time(start)}–${time(end)}`:'MyMecra'}</small></div><div class="player-controls"><button id="clipSlow" aria-pressed="false" aria-label="Yavaş dinleme">0.75×</button><button id="clipLoop" aria-pressed="false" aria-label="Beyti döngüde dinle">↻ Tekrar</button></div></div><div class="player-timeline"><span id="clipTime">0:00</span><input type="range" id="clipSeek" min="0" max="${end-start}" value="0" step="0.1" aria-label="Beyit içindeki konum"><span>${time(end-start)}</span></div><div class="source-line"><span id="playerStatus">Beyit aralığı yaklaşık; altyazı zamanlarına dayanır.</span><a href="${esc(clip?.watchUrl||c.source)}" target="_blank" rel="noopener">Asıl kayıtta aç ↗</a></div><div class="video-container" id="videoContainer" hidden><div id="youtubePlayer"></div></div>`;
  $('#recordName').onclick=()=>$('#clipPlay').click();
  clipLoop=false;slow=false;
  const setStatus=t=>{if($('#playerStatus'))$('#playerStatus').textContent=t};
  $('#clipLoop').onclick=e=>{clipLoop=!clipLoop;e.currentTarget.setAttribute('aria-pressed',clipLoop);toast(clipLoop?'Beyit tamamlanınca yeniden başlayacak.':'Tekrar kapatıldı.')};
  $('#clipSlow').onclick=e=>{slow=!slow;e.currentTarget.setAttribute('aria-pressed',slow);if(ytPlayer?.setPlaybackRate)ytPlayer.setPlaybackRate(slow ? 0.75 : 1);toast(slow?'Yavaş okuyuş seçildi.':'Normal hız seçildi.')};
  $('#clipSeek').oninput=e=>{if(ytPlayer?.seekTo)ytPlayer.seekTo(start+Number(e.target.value),true)};
  $('#clipPlay').onclick=async()=>{audioIntent='recording';stopTones();if(ytPlayer?.getPlayerState){if(ytPlayer.getPlayerState()===1)ytPlayer.pauseVideo();else{if(ytPlayer.getCurrentTime()>=end-.3)ytPlayer.seekTo(start,true);ytPlayer.playVideo()}return}
   const epoch=++playerEpoch;$('#clipPlay').disabled=true;setStatus('Asıl kayıt açılıyor…');$('#videoContainer').hidden=false;
   try{await loadYT();if(epoch!==playerEpoch||!$('#youtubePlayer'))return;ytPlayer=new YT.Player('youtubePlayer',{host:'https://www.youtube-nocookie.com',videoId:c.video,width:'560',height:'315',playerVars:{playsinline:1,rel:0,start:Math.floor(start),origin:location.origin},events:{onReady:e=>{if(epoch!==playerEpoch)return;e.target.seekTo(start,true);e.target.setPlaybackRate(slow ? 0.75 : 1);if(audioIntent==='recording')e.target.playVideo();else e.target.pauseVideo();$('#clipPlay').disabled=false;setStatus('Yaklaşık satır takibi · asıl kayıt');playerTimer=setInterval(()=>{if(!ytPlayer?.getCurrentTime||epoch!==playerEpoch)return;const t=ytPlayer.getCurrentTime();if($('#clipSeek'))$('#clipSeek').value=Math.max(0,t-start);if($('#clipTime'))$('#clipTime').textContent=time(t-start);$$('[data-poem-line]').forEach(el=>{const cue=clip?.lineCues?.[Number(el.dataset.poemLine)];el.classList.toggle('reading',!!cue&&t>=cue.startSec&&t<cue.endSec)});if(t>=end&&ytPlayer.getPlayerState()===1){if(clipLoop)ytPlayer.seekTo(start,true);else ytPlayer.pauseVideo()}},150)},onStateChange:e=>{if(epoch!==playerEpoch)return;if(e.data===1){audioIntent='recording';stopTones()}const b=$('#clipPlay');if(b){b.textContent=e.data===1?'Ⅱ':'▶';b.setAttribute('aria-label',e.data===1?'Kaydı duraklat':'Beyti asıl kayıttan dinle');if($('#recordName'))$('#recordName').textContent=e.data===1?'Ⅱ Kaydı duraklat':'▶ Hayâtî İnanç’tan dinle'}},onError:()=>{if(epoch!==playerEpoch)return;setStatus('Bu kayıt burada oynatılamadı. Asıl kayıt bağlantısını kullanabilirsin.');if($('#clipPlay'))$('#clipPlay').disabled=false}}})}catch{setStatus('Oynatıcı yüklenemedi. Asıl kayıt bağlantısını kullanabilirsin.');if($('#clipPlay'))$('#clipPlay').disabled=false}
  };
 }
 let audioCtx=null,audioNodes=[],soundTimers=[],toneEpoch=0,toneOnStop=null;
 function stopTones(){toneEpoch++;audioNodes.forEach(n=>{try{n.stop()}catch{}});audioNodes=[];soundTimers.forEach(clearTimeout);soundTimers=[];$$('.pulse-mark.on').forEach(e=>e.classList.remove('on'));const done=toneOnStop;toneOnStop=null;done?.()}
 function stopMedia(){audioIntent=null;playerEpoch++;clearInterval(playerTimer);playerTimer=null;if(ytPlayer){try{ytPlayer.destroy()}catch{}ytPlayer=null}window.speechSynthesis?.cancel();stopTones()}
 async function playPattern(pattern,tempo=86,onStop=null){
  stopTones();if(!pattern)return false;audioIntent='rhythm';ytPlayer?.pauseVideo?.();const epoch=toneEpoch;const Ctx=window.AudioContext||window.webkitAudioContext;
  if(!Ctx){toast('Bu tarayıcı ritim sesini desteklemiyor.');return false}
  try{audioCtx||=new Ctx();await audioCtx.resume();if(epoch!==toneEpoch)return false;toneOnStop=onStop;
   let t=audioCtx.currentTime+.05,delay=50;
   [...pattern].forEach((mark,i)=>{const duration=30/tempo*(mark==='L'?2:1),o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=mark==='L'?330:495;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(.14,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration*.9);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+duration);audioNodes.push(o);soundTimers.push(setTimeout(()=>{if(epoch===toneEpoch)$$('.pulse-mark').forEach((el,j)=>el.classList.toggle('on',j===i))},delay));t+=duration;delay+=duration*1000});
   soundTimers.push(setTimeout(()=>{if(epoch===toneEpoch)stopTones()},delay));return true;
  }catch{if(epoch===toneEpoch)stopTones();toast('Ritim başlatılamadı. Oynat düğmesine yeniden dokun.');return false}
 }
 function renderRhythms(){window.renderFailatunRhythms({esc,marks:E.marks,playPattern,stopTones,newEar,resetBuilder})}
 function renderPlay(){window.AruzPlay.render({chapters:base.chapters.map(chapterData),getLines:chapterLines,esc,marks:E.marks,playPattern,stopTones,sourceLinks,copyText,onChapter:id=>{state.chapter=id;state.panel='anlam';meclisMode='guided';save();location.hash='meclis'},onCollect:id=>{if(!state.bookmarks.includes(id)){state.bookmarks.push(id);save()}}})}
 const LEVELS={baslangic:'Başlangıç',orta:'Orta',ileri:'İleri'};
 function renderLessons(){
  const group=lessons.filter(l=>l.level===state.level);let current=group.find(l=>l.id===state.lesson)||group.find(l=>!state.completed.includes(l.id))||group[0];state.lesson=current.id;
  $('#main').innerHTML=intro('ADIM ADIM ARUZ','Kulağın alışsın. Gözün seçsin.','On iki kısa ders. Her adımda bir fikir, bir misal ve öğrendiğini sınayan iki soru.')+`<div class="level-tabs" aria-label="Ders seviyesi">${Object.entries(LEVELS).map(([id,title])=>`<button data-level="${id}" class="${id===state.level?'active':''}" aria-pressed="${id===state.level}">${title} <span class="subtle">${lessons.filter(l=>l.level===id&&state.completed.includes(l.id)).length}/4</span></button>`).join('')}</div><div class="lessons-layout"><aside><div class="lesson-list">${group.map((l,i)=>`<button class="lesson-link ${l.id===current.id?'active':''}" data-lesson="${l.id}" aria-pressed="${l.id===current.id}"><span>${state.completed.includes(l.id)?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${esc(l.title)}</strong><small>${state.completed.includes(l.id)?'Tamamlandı':'3–5 dakika · 2 soru'}</small></span></button>`).join('')}</div><div class="progress-track" aria-label="Ders ilerlemesi"><span style="width:${state.completed.length/lessons.length*100}%"></span></div><p class="subtle" id="lessonSummary" style="margin-top:12px">${state.completed.length} / ${lessons.length} ders tamamlandı.<br>İlerlemen bu tarayıcıda saklanır.</p>${state.mistakes.length?`<div class="note-box"><b>Tekrar zamanı</b><br>${state.mistakes.length} soru seni bekliyor.<br><button class="text-button" id="openReview">Tekrar defterini aç →</button></div>`:''}</aside><article class="lesson-content" id="lessonContent"></article></div>`;
  $$('[data-level]').forEach(b=>b.onclick=()=>{state.level=b.dataset.level;state.lesson=null;save();renderLessons()});$$('[data-lesson]').forEach(b=>b.onclick=()=>{state.lesson=b.dataset.lesson;save();renderLessons()});if($('#openReview'))$('#openReview').onclick=renderReview;renderLessonContent(current);
 }
 function renderLessonContent(l){
  $('#lessonContent').innerHTML=`<span class="eyebrow">${LEVELS[l.level]} · ${lessons.indexOf(l)+1} / ${lessons.length}</span><h2>${esc(l.title)}</h2><p class="meaning-detail">${esc(l.summary)}</p><div class="lesson-body">${l.body.map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="lesson-example">${esc(l.example)}</div><p class="subtle"><b>Bu dersin hedefi:</b> ${esc(l.objective)}</p>${l.questions.map((q,qi)=>`<section class="quiz-block" data-quiz="${qi}"><span class="mini-label">SIRA SENDE · ${qi+1}/2</span><h3>${esc(q.prompt)}</h3><div class="quiz-options">${q.choices.map((ch,ci)=>`<button data-answer="${ci}" data-question="${qi}">${esc(ch)}</button>`).join('')}</div><div class="feedback" role="status" id="feedback-${qi}"></div></section>`).join('')}<div class="action-row"><button class="primary" id="nextLesson">Sonraki ders →</button><button class="text-button" id="shareLesson">Ders bağlantısını kopyala ↗</button></div><p class="subtle" id="completionNote" style="margin-top:14px"></p><details class="source-list"><summary>Bu dersin kaynakları</summary>${sourceLinks(l.sourceIds)}</details>`;
  const applyAnswers=()=>{l.questions.forEach((q,qi)=>{const id=l.id+':'+qi,answer=state.answers[id],buttons=$$(`[data-question="${qi}"]`);buttons.forEach(b=>{const choice=Number(b.dataset.answer);b.classList.toggle('correct',answer===q.answer&&choice===q.answer);b.classList.toggle('wrong',answer!==undefined&&answer!==q.answer&&choice===answer);b.disabled=answer===q.answer});const f=$('#feedback-'+qi);if(answer!==undefined){f.className='feedback '+(answer===q.answer?'good':'bad');f.textContent=(answer===q.answer?'Doğru. ':'Bir daha düşün. ')+q.explanation}});const done=l.questions.every((q,qi)=>state.answers[l.id+':'+qi]===q.answer);$('#nextLesson').disabled=!done;$('#completionNote').textContent=done?'Bu dersi tamamladın. Hazırsan bir sonraki adıma geç.':'İki soruyu da doğru cevaplayınca ders tamamlanır.';if(done&&!state.completed.includes(l.id)){state.completed.push(l.id);save();const nav=$(`[data-lesson="${l.id}"]`);if(nav){nav.querySelector('span').textContent='✓';nav.querySelector('small').textContent='Tamamlandı'}const bar=$('.progress-track span');if(bar)bar.style.width=state.completed.length/lessons.length*100+'%';if($('#lessonSummary'))$('#lessonSummary').innerHTML=state.completed.length+' / '+lessons.length+' ders tamamlandı.<br>İlerlemen bu tarayıcıda saklanır.'}};
  $$('[data-answer]').forEach(b=>b.onclick=()=>{const qi=Number(b.dataset.question),choice=Number(b.dataset.answer),q=l.questions[qi],id=l.id+':'+qi;state.answers[id]=choice;if(choice===q.answer)state.mistakes=state.mistakes.filter(x=>x.id!==id);else if(!state.mistakes.some(x=>x.id===id))state.mistakes.push({id,lesson:l.id,question:qi});save();applyAnswers()});
  $('#nextLesson').onclick=()=>{const next=lessons[lessons.indexOf(l)+1];if(next){state.level=next.level;state.lesson=next.id;save();renderLessons();$('#lessonContent').scrollIntoView({block:'start'})}else showDialog(`<h2>Şimdi şiire geri dön.</h2><p>On iki dersi tamamladın. Bir meclis seç; bu kez uzun ve kısa hecelerin hangi işlemlerle yerleştiğini kendin izah etmeyi dene.</p><a class="primary" href="#meclis" id="finishToMeclis">Şiir meclisine geç →</a>`);if($('#finishToMeclis'))$('#finishToMeclis').onclick=()=>$('#infoDialog').close()};
  $('#shareLesson').onclick=()=>copyText(siteLink({ders:l.id},'dersler'));applyAnswers();
 }
 function renderReview(){showDialog(`<h2>Tekrar defterin</h2><p>Yanlış cevapladığın soruları yeniden aç. Doğru cevapladığında buradan kalkar.</p><ul class="review-list">${state.mistakes.map(m=>{const l=lessons.find(l=>l.id===m.lesson);return l?`<li><span>${esc(l.questions[m.question]?.prompt)}</span><button data-review="${l.id}">Derse git →</button></li>`:''}).join('')||'<li>Bekleyen sorun yok.</li>'}</ul>`);$$('[data-review]').forEach(b=>b.onclick=()=>{const l=lessons.find(l=>l.id===b.dataset.review);state.lesson=l.id;state.level=l.level;save();$('#infoDialog').close();renderLessons()})}
 async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Bağlantı kopyalandı.')}catch{showDialog(`<h2>Bağlantıyı kopyala</h2><p>Aşağıdaki bağlantıyı seçip kopyalayabilirsin.</p><input class="search" style="width:100%" readonly value="${esc(text)}" aria-label="Paylaşılabilir bağlantı">`)}}
 function renderLab(){const initial=scanPrefill||scanText;scanPrefill='';
  $('#main').innerHTML=intro('TAKTÎ LABORATUVARI','Bir mısrayı birlikte açalım.','Kaynaklı beyitlerde izahlı taktîyi gör. Kendi mısranda hecelemeyi ve muhtemel okumaları karşılaştır.')+`<div class="lab-layout"><section class="surface"><label class="field-label" for="scannerText">TEK BİR MISRA</label><textarea class="lab-input" id="scannerText" maxlength="240" spellcheck="false" placeholder="Meselâ: Saçma ey göz eşkden gönlümdeki odlara su">${esc(initial)}</textarea><div class="sample-chips">${[['muhibbi-1','Muhibbî'],['fuzuli-1','Su Kasidesi'],['galib-1','Şeyh Gâlib'],['hasim-1','Ahmet Hâşim']].map(([id,t])=>`<button data-sample="${id}">${t}</button>`).join('')}</div><div class="action-row"><button class="primary" id="scanButton">Mısrayı incele →</button><span class="subtle">Metin bu tarayıcıda işlenir.</span></div><details class="source-list"><summary>Serbest taktî ayarları</summary><div class="action-row"><label><input type="checkbox" id="allowVasl" checked> Vaslı dene</label><label><input type="checkbox" id="allowImale" checked> İmâleyi dene</label><label><input type="checkbox" id="allowMed" checked> Medi dene</label></div><p>Vaslın mümkün olduğu her yerde yapılması gerekmez; her bağı ayrı ayrı deneriz. Bu işlemler otomatik bir kesinlik sağlamaz. Zihaf otomatik tatbik edilmez.</p></details><div class="scan-result" id="scanResult"><p class="muted">${allLines.length} kaynaklı mısradan birini seçerek başlayabilirsin.</p></div></section><aside class="lab-aside simplified"><div class="surface lab-listening-link"><span class="eyebrow">RİTİM Mİ DİNLEMEK İSTİYORSUN?</span><h3>Dinleme ekranına geç.</h3><p>Sekiz ritmi dinle, yavaşlat ve kulağınla karşılaştır.</p><a class="primary" href="#ritimler">▶ Ritimleri dinle</a></div></aside></div>`;
  $('#scanButton').onclick=()=>runScan();$('#scannerText').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')runScan()};$$('[data-sample]').forEach(b=>b.onclick=()=>{const l=allLines.find(l=>l.id===b.dataset.sample);if(l){$('#scannerText').value=l.text;runScan()}});['allowVasl','allowImale','allowMed'].forEach(id=>$('#'+id).onchange=()=>{if(scanText)runScan()});
  if(initial)runScan();
 }
 function runScan(manual=false){scanText=$('#scannerText').value;const result=E.analyze(scanText,{corpus,meters:base.meters,manualTokens:manual?scanTokens:null,allowVasl:$('#allowVasl').checked,allowImale:$('#allowImale').checked,allowMed:$('#allowMed').checked});const out=$('#scanResult');
  if(result.kind==='invalid'||result.kind==='empty'){out.innerHTML=`<div class="empty" role="status">${esc(result.message)}</div>`;return}
  if(result.kind==='known'){const l=result.line;scanTokens=l.feet.flatMap(f=>f.syllables.map(s=>({...s,medEligible:s.mark==='LS'})));out.innerHTML=`<div class="result-header"><h3>Kaynaklı taktî misali</h3><span class="badge verified">${l.syllableCount||scanTokens.length} hece · ${l.pattern.length} vezin konumu</span></div><p class="subtle">Bu mısra, incelenmiş misaller arasındadır. Aşağıdaki kaynak metne dayanan taktî, bir benzerlik tahmini değildir.</p><div class="meter-title" style="margin-top:18px"><h3>${esc(l.meterRealization)}</h3></div>${scanMarkup(l)}<div class="note-box operation-detail"><b>Bir heceye dokun</b><br>Tabiî uzunluk ile vezindeki değerin niçin farklı olabildiğini gör.</div>${(l.notes||[]).map(n=>`<p class="subtle" style="margin-top:12px">${esc(n)}</p>`).join('')}<div class="action-row"><button class="secondary" id="resultPulse">◖ Kalıbı dinle</button><button class="text-button" id="editKnown">Hecelemeyi kendim düzenleyeyim →</button></div><details class="source-list"><summary>Metin ve kalıp kaynakları</summary>${sourceLinks(l.sourceIds)}</details>`;bindSyllables(out);$('#resultPulse').onclick=()=>playPattern(l.pattern);$('#editKnown').onclick=()=>paintExploratory(E.analyze(scanText,{corpus,meters:base.meters,manualTokens:scanTokens}),true);return}
  scanTokens=result.tokens;paintExploratory(result,manual);
 }
 function paintExploratory(result,manual){const out=$('#scanResult');out.innerHTML=`<div class="result-header"><h3>${manual?'Senin hecelemen':'Serbest ön inceleme'}</h3><span class="badge">Kesin hüküm değildir</span></div><p class="subtle">${esc(result.message)}</p><div class="manual-tokens">${scanTokens.map((s,i)=>`<button data-token="${i}" aria-label="${esc(s.text)} hecesinin değerini değiştir"><span>${esc(s.text)}</span><small>${E.marks(s.mark)}</small></button>`).join('')}</div><p class="subtle">Heceye dokunarak kısa → uzun → med değerini değiştir. Bölmek veya birleştirmek için aşağıdaki hecelemeyi düzenle.</p><label class="field-label" for="manualSyllables" style="display:block;margin-top:14px">Hecelerin arasına · koy</label><input class="search" style="width:100%;margin-top:8px" id="manualSyllables" value="${esc(scanTokens.map(s=>s.text).join(' · '))}"><button class="secondary" id="applySyllables" style="margin-top:10px">Hecelemeyi tatbik et</button><div class="note-box"><b>Muhtemel okumalar</b><br>İmâle ve med önerilerini kelimenin doğru söyleyişiyle denetle. Kalıbın çıkmaması mısranın kusurlu olduğunu göstermez. Tarihî telaffuzu, izinli tef‘ile değişmelerini ve şiirin diğer mısralarını da karşılaştır. Bu alan her mısrayı ayrı inceler; şiirin bütününden ortak bir vezin tespit etmez.</div><div style="margin-top:20px">${result.candidates.length?result.candidates.map((c,i)=>`<div class="candidate"><h3>${esc(c.name)}</h3><p>${E.marks(c.pattern)}</p><p>${c.operations.length?c.operations.map(o=>`${esc(o.text)}: ${o.type==='med'?'med ihtimali':'imâle ihtimali'}`).join(' · '):'Bu hece değerleriyle ek imâle veya med gerekmiyor.'}${c.junctions.length?`<br>Denenecek bağlar: ${c.junctions.map(esc).join(' · ')}`:''}</p><button class="text-button" data-candidate="${i}">◖ Bu düzeni dinle</button></div>`).join(''):'<p class="muted">Şimdilik kalıp önermiyoruz. Kaynaklı bir misalle karşılaştırabilir veya hecelemeyi düzeltebilirsin.</p>'}</div>`;
  const rerun=()=>{const r=E.analyze(scanText,{corpus,meters:base.meters,manualTokens:scanTokens});paintExploratory(r,true)};$$('[data-token]').forEach(b=>b.onclick=()=>{const s=scanTokens[Number(b.dataset.token)];s.mark={S:'L',L:'LS',LS:'S'}[s.mark];rerun()});$('#applySyllables').onclick=()=>{const items=$('#manualSyllables').value.split(/[·|]/).map(s=>s.trim()).filter(Boolean);if(items.length<4||items.some(s=>!/[aeıioöuüâîû]/i.test(s))){toast('Her parçada bir hece olacak şekilde en az dört hece yaz.');return}scanTokens=items.map((text,i)=>{const parsed=E.tokenize(text).tokens;if(parsed.length!==1)return null;const s=parsed[0];return {...s,mark:i===items.length-1?'L':s.natural}});if(scanTokens.some(s=>!s)){toast('Birden çok sesli harf taşıyan parçaları · ile ayır.');scanTokens=E.tokenize(scanText).tokens;return}rerun()};$$('[data-candidate]').forEach(b=>b.onclick=()=>playPattern(result.candidates[Number(b.dataset.candidate)].pattern));
 }
 const earFeet=[['Fâilâtün','LSLL'],['Mefâîlün','SLLL'],['Feûlün','SLL'],['Fâilün','LSL'],['Mef‘ûlü','LLS']];let earAnswer;
 function newEar(){earAnswer=earFeet[Math.floor(Math.random()*earFeet.length)];const choices=[earAnswer,...earFeet.filter(x=>x!==earAnswer).sort(()=>Math.random()-.5).slice(0,2)].sort(()=>Math.random()-.5);$('#earOptions').innerHTML=choices.map(x=>`<button data-ear="${x[0]}">${x[0]}</button>`).join('');$('#earFeedback').textContent='';$('#earPlay').onclick=()=>playPattern(earAnswer[1],80);$$('[data-ear]').forEach(b=>b.onclick=()=>{const good=b.dataset.ear===earAnswer[0];$('#earFeedback').className='feedback '+(good?'good':'bad');$('#earFeedback').textContent=good?`Doğru: ${earAnswer[0]} = ${E.marks(earAnswer[1])}`:`Bu ritim ${earAnswer[0]}: ${E.marks(earAnswer[1])}. Tekrar dinleyip süreleri karşılaştır.`})}
 function resetBuilder(){const pool=[['söz','L'],['gü','S'],['bir','L'],['zel','L']],chosen=[];$('#builderButtons').innerHTML=pool.map(([s,k],i)=>`<button data-builder="${i}">${s}</button>`).join('');$('#builderResult').textContent='Dört heceyi sırayla seç.';$$('[data-builder]').forEach(b=>b.onclick=()=>{const s=pool[Number(b.dataset.builder)];if(s[1]!=='LSLL'[chosen.length]){toast('Bu yuvada '+('LSLL'[chosen.length]==='L'?'uzun':'kısa')+' hece gerekiyor.');return}chosen.push(s[0]);b.disabled=true;$('#builderResult').textContent=chosen.join(' · ')+(chosen.length===4?' = Fâilâtün ✓':'');if(chosen.length===4)playPattern('LSLL')})}
 function renderArchive(){
  $('#main').innerHTML=intro('KAYIT ARŞİVİ','Bir beyitten ötekine.','Hayâtî İnanç’ın asıl kayıtlarını şair ve konuya göre keşfet. Meclis işaretli kayıtlarda beyti birlikte çözebilirsin.')+`<div class="archive-controls"><input class="search" id="archiveSearch" type="search" aria-label="Şair, beyit veya konu ara" placeholder="Şair, beyit veya konu ara…"><select id="archiveSeries" aria-label="Kayıt serisi"><option value="all">Bütün seriler</option><option>Hayâtî Beyitler</option><option>Can Veren Pervaneler</option></select><label class="subtle"><input type="checkbox" id="savedOnly"> Defterim</label></div><p class="subtle" id="archiveCount" aria-live="polite"></p><div class="archive-list" id="archiveGrid" style="margin-top:18px"></div>`;
  ['archiveSearch','archiveSeries','savedOnly'].forEach(id=>$('#'+id).addEventListener(id==='archiveSearch'?'input':'change',paintArchive));paintArchive();
 }
 function paintArchive(){const query=E.normalize($('#archiveSearch').value),series=$('#archiveSeries').value,only=$('#savedOnly').checked;
  const records=base.records.map(r=>{const chapter=base.chapters.find(c=>c.source===r.source);const data={...r,source:archiveFixes[r.id]||r.source,chapter:chapter?.id};if(r.id==='hb01'){data.title='Türkçenin En Güzel Naatı';data.quote='Men lebün müştâkıyam zühhâd Kevser tâlibi';data.desc='Su Kasidesi’nin onuncu beyti: iştiyak, Kevser ve aşkın dili.'}return data}).filter(r=>(!query||E.normalize([r.title,r.poet,r.theme,r.desc,r.quote||''].join(' ')).includes(query))&&(series==='all'||r.series===series)&&(!only||state.bookmarks.includes(r.id)||state.bookmarks.includes(r.chapter)));
  $('#archiveCount').textContent=`${records.length} kayıt · Kaynak bağlantıları resmî yayınlara gider.`;$('#archiveGrid').innerHTML=records.length?records.map(r=>`<article class="record-card"><div class="record-series">${esc(r.series.toLocaleUpperCase('tr-TR'))} · ${esc(r.episode)}</div><h3>${esc(r.title)}</h3><p>${esc(r.poet)} · ${esc(r.theme)}</p><p style="margin-top:10px">${esc(r.desc)}</p><div class="record-bottom">${r.chapter?`<button class="text-button" data-open-chapter="${r.chapter}">Beyti aç →</button>`:`<a href="${esc(r.source)}" target="_blank" rel="noopener">Asıl kaydı dinle ↗</a>`}<button class="bookmark" data-save-record="${r.id}" aria-label="${esc(r.title)} kaydını deftere ekle" aria-pressed="${state.bookmarks.includes(r.id)||state.bookmarks.includes(r.chapter)}">${state.bookmarks.includes(r.id)||state.bookmarks.includes(r.chapter)?'★':'☆'}</button></div>${r.chapter?`<a class="subtle" style="margin-top:12px" href="${esc(r.source)}" target="_blank" rel="noopener">Tam kayda git ↗</a>`:''}</article>`).join(''):'<div class="empty">Bu aramayla kayıt bulunamadı. Şair adıyla veya daha kısa bir kelimeyle dene.</div>';
  $$('[data-open-chapter]').forEach(b=>b.onclick=()=>{state.chapter=b.dataset.openChapter;save();location.hash='meclis'});$$('[data-save-record]').forEach(b=>b.onclick=()=>{const r=records.find(r=>r.id===b.dataset.saveRecord);const id=state.bookmarks.includes(r.chapter)?r.chapter:r.id;toggleBookmark(id);paintArchive()});
 }
 function renderTeacher(){const c=chapterData(getChapter()),lines=chapterLines(c.id);
  $('#main').innerHTML=intro('HOCANIN MASASI','Sınıfta bir şiir meclisi.','Kırk dakikalık ders akışını aç; seçtiğin beyte ait çalışma kâğıdını yazdır veya meclisi tahtaya yansıt.')+`<div class="teacher-form"><select id="teacherChapter" aria-label="Ders için beyit seç">${base.chapters.map(ch=>`<option value="${ch.id}" ${ch.id===c.id?'selected':''}>${esc(ch.poet)}</option>`).join('')}</select><button class="primary" id="printSheet">Çalışma kâğıdını yazdır</button><button class="secondary" id="projectorButton">Tahta görünümü ↗</button><button class="secondary" id="shareChapter">Beyit bağlantısını kopyala</button></div><div class="teacher-grid" style="margin-top:25px"><section class="surface teacher-plan"><span class="eyebrow">40 DAKİKALIK AKIŞ</span><h2>${esc(c.poet)} meclisi</h2><ol class="timeline">${[['00–05','Kulağı aç','Kalıbın ritmini dinlet. Kısa ve uzun değerleri parmak vuruşlarıyla ayırt edin.'],['05–12','Ustadan dinle','Beyit kesitini dinlet. Ardından tam kayıttaki anlatımı aç; talebeler duydukları kelimeleri not etsin.'],['12–20','Kelimeleri aç',c.prompts[0]+'. Her talebe önce kendi fikrini söylesin.'],['20–32','Birlikte çöz','İki mısrayı tef‘ilelere bölün. İmâle, med, ulama ve mısra sonu izahlarını hecelere dokunarak inceleyin.'],['32–40','Öğrendiğini göster','Çalışma kâğıdını tamamlat. Her talebe bir hecenin aldığı değeri ve bunun sebebini izah etsin.']].map(([t,h,d])=>`<li><time>${t}</time><div><strong>${h}</strong><p>${esc(d)}</p></div></li>`).join('')}</ol><div class="note-box"><b>Cevapları dinlerken</b><br>Yalnız doğru işareti değil, talebenin izahını dinle. Serbest inceleme bir kalıp bulamazsa bunu talebenin hatası sayma.</div></section><section class="worksheet" id="worksheet"><span class="eyebrow">FÂİLÂTÜN · ${esc(c.poet)}</span><h3>Şiirin nabzını işaretle</h3><p>Adı ve soyadı: ____________________<br>Tarih: ________________________</p><p><b>1. Heceleri tanı.</b> ka · lem · gül · de<br>Her hecenin altına kısa (⏑) veya uzun (—) yaz.</p><div class="answer-line"></div><p><b>2. Beyti oku.</b><br>${c.lines.map(esc).join('<br>')}</p><p><b>3. İlk mısrayı tef‘ilelere ayır.</b> Bir aruz işlemi seç; niçin gerektiğini izah et.</p><div class="answer-line"></div><div class="answer-line"></div><p><b>4. Manayı kendi sözlerinle anlat.</b> Beyitten iki kelime seç ve manalarını yaz.</p><div class="answer-line"></div><div class="answer-line"></div><details><summary>Hoca için cevap anahtarı</summary><p>1. ⏑ — — ⏑<br>3. ${esc(lines[0]?.meterRealization||c.meter)}<br>${esc(lines[0]?.notes?.join(' ')||'Taktî haritasındaki hece izahlarına bakınız.')}<br>4. ${esc(c.meaning)}</p></details><p class="subtle print-only">${esc(siteBase.host+siteBase.pathname.replace(/\/$/,''))}</p></section></div>`;
  $('#teacherChapter').onchange=e=>{state.chapter=e.target.value;save();renderTeacher()};$('#printSheet').onclick=()=>window.print();$('#shareChapter').onclick=()=>copyText(siteLink({beyit:c.id},'meclis'));$('#projectorButton').onclick=()=>{document.body.classList.add('projector');state.panel='takti';location.hash='meclis';const exit=document.createElement('button');exit.className='projector-exit';exit.textContent='Tahta görünümünden çık ✕';exit.onclick=()=>{document.body.classList.remove('projector');exit.remove()};document.body.append(exit)};
 }
 function render(){if(!ready)return;route=location.hash.replace('#','').split('?')[0]||'kesfet';if(!['kesfet','oyna','ritimler','meclis','dersler','laboratuvar','arsiv','ogretmen'].includes(route))route='kesfet';$$('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===route);if(a.dataset.route===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#toolsNav').open=false;$('#toolsNav summary').classList.toggle('active',['laboratuvar','arsiv','ogretmen'].includes(route));window.AruzPlay?.dispose();stopMedia();document.body.classList.toggle('brand-route',route==='kesfet');if(route==='kesfet'){const chapter=chapterData(base.chapters.find(c=>c.id==='muhibbi'));window.renderFailatunHome({chapter,line:chapterLines('muhibbi')[0],esc,renderPlayer,playPattern,openChapter:()=>{state.chapter='muhibbi';state.panel='anlam';meclisMode='guided';save();location.hash='meclis'}});renderStudyReturn()}else if(route==='oyna')renderPlay();else if(route==='ritimler')renderRhythms();else if(route==='meclis')renderMeclis();else if(route==='dersler')renderLessons();else if(route==='laboratuvar')renderLab();else if(route==='arsiv')renderArchive();else renderTeacher();document.body.classList.toggle('worksheet-mode',route==='ogretmen')}
 $('#toolsNav').addEventListener('keydown',e=>{if(e.key==='Escape'){$('#toolsNav').open=false;$('#toolsNav summary').focus()}});document.addEventListener('click',e=>{if(!$('#toolsNav').contains(e.target))$('#toolsNav').open=false});
 $('.skip').onclick=e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView()};
 addEventListener('hashchange',()=>{render();scrollTo({top:0,behavior:'instant'})});
 $('#main').innerHTML='<p class="loading-message">Şiir meclisi açılıyor…</p>';
 Promise.all(['corpus.json','lessons.json','recordings.json','archive-fixes.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw new Error('data');return r.json()}))).then(([c,l,r,a])=>{corpus=c;lessons=l.lessons;lessonSources=l.sources;recordings=Object.fromEntries(r.clips.map(x=>[x.id,x]));archiveFixes=a;allLines=E.flattenCorpus(c);ready=true;state.completed=state.completed.filter(id=>lessons.some(l=>l.id===id));const params=new URLSearchParams(location.search);if(base.chapters.some(ch=>ch.id===params.get('beyit')))state.chapter=params.get('beyit');if(lessons.some(l=>l.id===params.get('ders'))){state.lesson=params.get('ders');state.level=lessons.find(l=>l.id===state.lesson).level}render();updateProgress()}).catch(()=>{$('#main').innerHTML='<div class="empty"><h2>Meclis yüklenemedi.</h2><p>Bağlantını kontrol edip yeniden dene.</p><button class="secondary" id="reloadPage">Yeniden dene</button></div>';$('#reloadPage').onclick=()=>location.reload()});
})();
