// Silsile-i Aliyye — Nakşibendiyye Altın Zinciri
// 30 Halka: Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'dan
//           Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh)'ya

const SILSILE = [
  {
    id: 1,
    ad: "Hazret-i Muhammed Mustafâ",
    tam_ad: "Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)",
    lakap: "Habîbullâh, Hâtemü'l-Enbiyâ, Seyyidü'l-Mürselîn, Rahmeten li'l-Âlemîn",
    asir: "VII. Yüzyıl",
    dogum: "571", vefat: "632",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4672, 39.6119],
    biyografi: "Âlemlere rahmet olarak gönderilen Allahu Teâlâ'nın son peygamberi ve en sevgili kuludur. Her velînin velâyeti, her tarikatın silsilesi ve her mürşidin feyz ü nuru nihayetinde ona dayanır; o kapıya ulaşır. Nakşibendiyye'nin bu altın zinciri de onun mübarek kaynağından akar. Silsiledeki her isim, o nurü nesilden nesile taşıyan birer emânettir; her halka, onun sohbetinin ve nefesinin bir yansımasıdır. Mekke-i Mükerreme'de doğmuş, Medîne-i Münevvere'de Ravza-i Mutahhara'ya teşrif buyurmuştur. Ashâb-ı Kirâm'ın, Tâbiîn'in ve kıyamete dek gelecek bütün ümmetin kalpleri o kapıya bağlıdır.",
    portre: null
  },
  {
    id: 2,
    ad: "Hazret-i Ebû Bekir es-Sıddık",
    tam_ad: "Hazret-i Ebû Bekir es-Sıddık (radıyallahu anh)",
    lakap: "es-Sıddık, Halifetü Resulillah",
    asir: "VII. Yüzyıl",
    dogum: "573", vefat: "634",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4672, 39.6119],
    biyografi: "Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'ın en yakın dostu, ilk erkek mümini ve İslam'ın ilk halifesidir. Nakşibendiyye'de manevi terbiyenin hafi (gizli) yoluyla aktarımı ondan başlar. Medîne-i Münevvere'de Ravza-i Mutahhara'nın yanı başında medfundur.",
    portre: null
  },
  {
    id: 3,
    ad: "Hazret-i Selmân-ı Fârisî",
    tam_ad: "Hazret-i Selmân-ı Fârisî (radıyallahu anh)",
    lakap: "Ebu Abdillah, Selmânü'l-Hayr",
    asir: "VII. Yüzyıl",
    dogum: "~568", vefat: "~656",
    sehir: "Selmânpâk (Medâin yakını)", ulke: "Irak", bolge: "Mezopotamya",
    koordinat: [33.0956, 44.7642],
    biyografi: "İran'ın İsfahan yakınlarında doğmuş, uzun bir manevi arayışın ardından Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'e kavuşmuştur. Peygamber Efendimiz (sallallahu aleyhi ve sellem) onun hakkında 'Selmân bizdendir, Ehl-i Beyt'tendir' buyurmuştur. Silsilede Faris'ten gelen manevi akışın taşıyıcısıdır. Türbesi Bağdat yakınında Selmânpâk'tadır.",
    portre: null
  },
  {
    id: 4,
    ad: "Hazret-i Kasım ibn Muhammed",
    tam_ad: "Hazret-i Kasım ibn Muhammed ibn Ebî Bekir (kuddise sirruh)",
    lakap: "Ebu Muhammed el-Medenî",
    asir: "VII–VIII. Yüzyıl",
    dogum: "~660", vefat: "~726",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4700, 39.6180],
    biyografi: "Hazret-i Ebû Bekir es-Sıddık (radıyallahu anh)'ın torunudur. Medîne-i Münevvere'nin ilim ve vera sahibi büyüklerindendi; fıkıh ve hadiste çağının imamı sayılmıştır. Manevi feyz Hazret-i Selmân-ı Fârisî (radıyallahu anh) vasıtasıyla ona ulaşmış, oradan Hazret-i Cafer-i Sâdık (kuddise sirruh)'a intikal etmiştir.",
    portre: null
  },
  {
    id: 5,
    ad: "Hazret-i Cafer-i Sâdık",
    tam_ad: "Hazret-i Cafer-i Sâdık (kuddise sirruh)",
    lakap: "es-Sâdık, İmâmü's-Sâdıkın",
    asir: "VIII. Yüzyıl",
    dogum: "702", vefat: "765",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4660, 39.6100],
    biyografi: "Hazret-i Ali (radıyallahu anh)'nin mübarek neslinden, Ehl-i Beyt'in büyük imamıdır. Hem zâhir hem bâtın ilimlerinde çağının pınarı idi; pek çok büyük alim ondan istifade etmiştir. Medîne-i Münevvere'de Bakî kabristanında medfundur.",
    portre: null
  },
  {
    id: 6,
    ad: "Hazret-i Bâyezîd-i Bistâmî",
    tam_ad: "Hazret-i Bâyezîd-i Bistâmî (kuddise sirruh)",
    lakap: "Sultânü'l-Ârifîn",
    asir: "IX. Yüzyıl",
    dogum: "~804", vefat: "~874",
    sehir: "Bistam", ulke: "İran", bolge: "Horasan",
    koordinat: [36.4174, 54.2850],
    biyografi: "İran'ın Bistam şehrinde doğup vefat etmiştir. 'Sultânü'l-Ârifîn' lakabıyla anılan büyük velîdir. İslam tasavvuf tarihinde fenâ fillah ve sekr makamını ilk sistematik biçimde dile getirenlerdendir. Türbesi Bistam'da hâlâ ziyaret edilmektedir.",
    portre: null
  },
  {
    id: 7,
    ad: "Hazret-i Ebü'l-Hasan Harakânî",
    tam_ad: "Hazret-i Ebü'l-Hasan Harakânî (kuddise sirruh)",
    lakap: "Şeyhü'l-İslâm",
    asir: "X–XI. Yüzyıl",
    dogum: "~963", vefat: "1033",
    sehir: "Hârakân", ulke: "İran", bolge: "Horasan",
    koordinat: [36.4500, 49.5000],
    biyografi: "Kazvin yakınlarındaki Hârakân köyünden yetişmiş büyük velîdir. Üveysî yolla Hazret-i Bâyezîd-i Bistâmî (kuddise sirruh)'den feyz almış; Muhyiddin İbnü'l-Arabî ve Ferîdüddin Attâr onu büyük övgüyle anmıştır. Türbesi hâlâ Hârakân'dadır.",
    portre: null
  },
  {
    id: 8,
    ad: "Hazret-i Ebû Alî Fârmedî",
    tam_ad: "Hazret-i Ebû Alî Fârmedî (kuddise sirruh)",
    lakap: "Kutbü'l-Aktâb",
    asir: "XI. Yüzyıl",
    dogum: "~1042", vefat: "1084",
    sehir: "Tûs (Nîşâbur yakını)", ulke: "İran", bolge: "Horasan",
    koordinat: [36.2719, 59.6134],
    biyografi: "İmam Gazzâlî'nin irşat yolculuğundaki mürşididir. Nişabur ve Tus'ta pek çok talebe yetiştirmiştir. Hem Nakşibendiyye hem de Kâdiriyye silsilelerinin önemli bir halkasıdır. Feyzini Hazret-i Ebü'l-Hasan Harakânî (kuddise sirruh)'den almıştır.",
    portre: null
  },
  {
    id: 9,
    ad: "Hazret-i Yûsuf-ı Hemedânî",
    tam_ad: "Hazret-i Yûsuf-ı Hemedânî (kuddise sirruh)",
    lakap: "Kutbü'l-Meşâyih",
    asir: "XI–XII. Yüzyıl",
    dogum: "1049", vefat: "1140",
    sehir: "Merv", ulke: "Türkmenistan", bolge: "Mâverâünnehr",
    koordinat: [37.6394, 62.1873],
    biyografi: "Hemedan doğumlu olup Merv'e yerleşmiştir. Hacegân silsilesinin Orta Asya'ya taşınmasındaki en büyük köprü mesabesindedir. Yetiştirdiği halifeler arasında Hazret-i Ahmed Yesevî (kuddise sirruh) ve Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh) bulunmakta olup bu iki isim Türk-İslam tasavvufunun iki büyük kanalını oluşturmuştur.",
    portre: null
  },
  {
    id: 10,
    ad: "Hazret-i Abdülhâlik Gücdevânî",
    tam_ad: "Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh)",
    lakap: "Hazret-i Hvâce",
    asir: "XII. Yüzyıl",
    dogum: "~1103", vefat: "1179",
    sehir: "Gücdevân (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [40.1047, 64.6801],
    biyografi: "Nakşibendiyye'nin temel prensiplerini (kelimât-ı kudsiyye) ilk defa bir bütün hâlinde ortaya koyan büyük mürşiddir. Gizli zikrin (zikr-i hafî) sistemini kurmuş; 'Dilde Hak, elde halk' düsturunu yaşamıştır. Buhara yakınlarındaki Gücdevân'da medfundur.",
    portre: null
  },
  {
    id: 11,
    ad: "Hazret-i Ârif-i Rîvegerî",
    tam_ad: "Hazret-i Ârif-i Rîvegerî (kuddise sirruh)",
    lakap: "Hvâce Ârif",
    asir: "XII–XIII. Yüzyıl",
    dogum: "?", vefat: "~1239",
    sehir: "Rîveger (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8000, 64.4500],
    biyografi: "Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh)'nin en has ve yüksek halifesidir. Buhara civarındaki Rîveger köyünde yaşamış ve orada defnedilmiştir. Silsilede derin sükûnet ve hakikat anlayışıyla temayüz etmiş büyük bir velîdir.",
    portre: null
  },
  {
    id: 12,
    ad: "Hazret-i Mahmûd-ı İncirfağnevî",
    tam_ad: "Hazret-i Mahmûd-ı İncirfağnevî (kuddise sirruh)",
    lakap: "Hvâce Mahmûd",
    asir: "XIII. Yüzyıl",
    dogum: "?", vefat: "~1272",
    sehir: "İncirfağne (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8500, 64.3000],
    biyografi: "Buhara'nın İncirfağne köyünden yetişmiş büyük velîdir. Moğol istilasının en şiddetli döneminde Mâverâünnehr'de tasavvuf ateşini canlı tutmuştur. Silsilenin bu karanlık dönemde kesintisiz devam etmesini sağlamıştır.",
    portre: null
  },
  {
    id: 13,
    ad: "Hazret-i Alî Râmitenî",
    tam_ad: "Hazret-i Alî Râmitenî (kuddise sirruh)",
    lakap: "Hvâce Azîzân",
    asir: "XIII–XIV. Yüzyıl",
    dogum: "~1195", vefat: "~1306",
    sehir: "Râmiten (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [40.0500, 64.3500],
    biyografi: "'Hvâce Azîzân' (Azizler Efendisi) lakabıyla tanınmıştır. Buhara yakınlarındaki Râmiten'de uzun yıllar mürid yetiştirmiştir. İlim, ahlak ve maneviyat bakımından döneminin başvuru kaynağı olan bu büyük velî yüz yaşını aşkın bir ömür sürmüştür.",
    portre: null
  },
  {
    id: 14,
    ad: "Hazret-i Muhammed Bâbâ Semmâsî",
    tam_ad: "Hazret-i Muhammed Bâbâ Semmâsî (kuddise sirruh)",
    lakap: "Hvâce Bâbâ",
    asir: "XIV. Yüzyıl",
    dogum: "?", vefat: "1354",
    sehir: "Semmâs (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8000, 64.6000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) mürşidinin mürşididir. Buhara civarındaki Semmâs köyündendir. Manevi terbiyedeki hassasiyeti ve derin hikmeti ile tanınmıştır. Halifesi Hazret-i Seyyid Emîr Külâl (kuddise sirruh) aracılığıyla bu nurlu emaneti devam ettirmiştir.",
    portre: null
  },
  {
    id: 15,
    ad: "Hazret-i Seyyid Emîr Külâl",
    tam_ad: "Hazret-i Seyyid Emîr Külâl (kuddise sirruh)",
    lakap: "Emîr-i Buhârâ",
    asir: "XIV. Yüzyıl",
    dogum: "~1312", vefat: "1370",
    sehir: "Suhâre (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7500, 64.5000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) hakiki ve baş mürşididir. Seyyid soyundan gelen bu büyük zât, hem ilim hem de manevi nüfuz bakımından döneminin en seçkin şahsiyetlerindendi. Buhara'ya bağlı Suhâre köyünde yaşamış ve orada medfundur.",
    portre: null
  },
  {
    id: 16,
    ad: "Hazret-i Muhammed Bahâeddin Nakşibend",
    tam_ad: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend (kuddise sirruh)",
    lakap: "Şâh-ı Nakşibend",
    asir: "XIV. Yüzyıl",
    dogum: "1318", vefat: "1389",
    sehir: "Kasr-ı Ârifân (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7744, 64.4325],
    biyografi: "Bu mübarek silsilenin adını taşıyan büyük velî ve Nakşibendiyye tarikatının kurucu imamıdır. 'Dilde Hak, elde halk' ve 'Halvet der encümen' prensiplerini hayatında mükemmel surette yaşamıştır. Hafi zikri esas almış, kalp ile zikrin ehemmiyetini öğretmiştir. Türbesi Buhara yakınındaki Kasr-ı Ârifân'dadır ve dünyanın dört bir yanından gelen hacı adayları ziyaret eder.",
    portre: null
  },
  {
    id: 17,
    ad: "Hazret-i Alâeddin-i Attâr",
    tam_ad: "Hazret-i Alâeddin-i Attâr (kuddise sirruh)",
    lakap: "Hvâce Alâeddin",
    asir: "XIV–XV. Yüzyıl",
    dogum: "~1340", vefat: "1400",
    sehir: "Cağânyân (Termiz yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [37.2000, 67.3000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) hem en yakın halifesi hem de damadıdır. Bu mübarek emanetin manevi varisi sıfatıyla silsileyi sonraki nesle taşımıştır. Termiz civarındaki Cağânyân bölgesinde medfundur.",
    portre: null
  },
  {
    id: 18,
    ad: "Hazret-i Yakûb-ı Çerhî",
    tam_ad: "Hazret-i Yakûb-ı Çerhî (kuddise sirruh)",
    lakap: "Hvâce Yakûb",
    asir: "XV. Yüzyıl",
    dogum: "~1359", vefat: "1447",
    sehir: "Hisar", ulke: "Tacikistan", bolge: "Mâverâünnehr",
    koordinat: [38.5236, 68.7786],
    biyografi: "Hazret-i Alâeddin-i Attâr (kuddise sirruh)'ın önde gelen halifesidir. Tacikistan'ın Hisar şehrinde uzun yıllar ikamet etmiş ve orada medfundur. İlim, zühd ve derin takvası sayesinde büyük saygınlık kazanmıştır.",
    portre: null
  },
  {
    id: 19,
    ad: "Hazret-i Ubeydullah Ahrâr",
    tam_ad: "Hazret-i Ubeydullah Ahrâr (kuddise sirruh)",
    lakap: "Hvâce Ahrâr",
    asir: "XV. Yüzyıl",
    dogum: "1404", vefat: "1490",
    sehir: "Semerkand", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.6542, 66.9597],
    biyografi: "Silsilenin Orta Asya'daki en güçlü halkalarından birini oluşturan bu büyük zât, Semerkand çevresinde hem manevi hem siyasi büyük nüfuz sahibi olmuştur. Timurlu hükümdarlarını ve devlet adamlarını irşat etmiş; döneminin siyasi hayatında İslam'ın hakkını korumuştur. Türbesi Semerkand yakınındadır.",
    portre: null
  },
  {
    id: 20,
    ad: "Hazret-i Muhammed Zâhid",
    tam_ad: "Hazret-i Muhammed Zâhid (kuddise sirruh)",
    lakap: "Hvâce Muhammed",
    asir: "XV–XVI. Yüzyıl",
    dogum: "?", vefat: "1529",
    sehir: "Semerkand", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7000, 66.8000],
    biyografi: "Hazret-i Ubeydullah Ahrâr (kuddise sirruh)'ın en değerli halifelerindendir. Semerkand bölgesinde talebe yetiştirmiş ve mübarek silsileyi sonraki nesle büyük bir sadakatle aktarmıştır. Zühd ve takvasıyla tanınan bu büyük velî Mâverâünnehr'de medfundur.",
    portre: null
  },
  {
    id: 21,
    ad: "Hazret-i Derviş Muhammed",
    tam_ad: "Hazret-i Derviş Muhammed (kuddise sirruh)",
    lakap: "Derviş Hvâce",
    asir: "XVI. Yüzyıl",
    dogum: "?", vefat: "1562",
    sehir: "Semerkand bölgesi", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.5000, 66.5000],
    biyografi: "Hazret-i Muhammed Zâhid (kuddise sirruh)'in halifesi ve bu mübarek silsilenin söz konusu dönemdeki taşıyıcısıdır. Orta Asya'da manevi irşat geleneğini büyük bir titizlikle sürdürmüş ve emaneti kâmil surette aktarmıştır.",
    portre: null
  },
  {
    id: 22,
    ad: "Hazret-i Hâce Emkinegî",
    tam_ad: "Hazret-i Muhammed Emkinegî (kuddise sirruh)",
    lakap: "Hvâce Emkine",
    asir: "XVI. Yüzyıl",
    dogum: "~1519", vefat: "1600",
    sehir: "Emkine (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.9000, 64.2000],
    biyografi: "Buhara yakınlarındaki Emkine köyünden büyük velîdir. Hazret-i Derviş Muhammed (kuddise sirruh)'den aldığı mübarek emaneti titizlikle korumuş; halifesi Hazret-i Muhammed Bâkibillâh (kuddise sirruh) aracılığıyla bu nurlu silsileyi Hindistan coğrafyasına taşıtmıştır.",
    portre: null
  },
  {
    id: 23,
    ad: "Hazret-i Muhammed Bâkibillâh",
    tam_ad: "Hazret-i Muhammed Bâkibillâh (kuddise sirruh)",
    lakap: "Bâkibillâh",
    asir: "XVI–XVII. Yüzyıl",
    dogum: "1564", vefat: "1603",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6139, 77.2090],
    biyografi: "Nakşibendiyye'yi Hindistan'a taşıyan ilk büyük mürşiddir. Semerkand'da tahsil ettiği manevi mirası Delhi'ye getirmiş; halifesi Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh) aracılığıyla tüm dünyaya yaymıştır. Delhi'de medfundur.",
    portre: null
  },
  {
    id: 24,
    ad: "Hazret-i Ahmed Fârûk Serhendî",
    tam_ad: "Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh)",
    lakap: "İmâm-ı Rabbânî, Müceddid-i Elf-i Sânî",
    asir: "XVI–XVII. Yüzyıl",
    dogum: "1564", vefat: "1624",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6341, 76.3953],
    biyografi: "'İkinci Binin Müceddidi' lakabını almış büyük alim ve velîdir. Mektûbât adlı eseri İslam tasavvuf literatürünün en değerli kaynakları arasında kabul edilmektedir. Hint Müslümanlarının İslami kimliğini muhafaza etmesinde ve Nakşibendî geleneğinin yeniden ihyasında tarihi bir rol üstlenmiştir. Serhend'de medfundur.",
    portre: null
  },
  {
    id: 25,
    ad: "Hazret-i Muhammed Mâsum",
    tam_ad: "Hazret-i Muhammed Mâsum (kuddise sirruh)",
    lakap: "Mâsum-ı Fârûkî",
    asir: "XVII. Yüzyıl",
    dogum: "1599", vefat: "1668",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6400, 76.4000],
    biyografi: "Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh)'nin üçüncü oğlu ve en önde gelen halifesidir. Babasından aldığı manevi mirası özümseyerek Hindistan, Orta Asya ve Osmanlı topraklarına yaymıştır. Çeşitli mektup ve eserleri günümüze ulaşmıştır.",
    portre: null
  },
  {
    id: 26,
    ad: "Hazret-i Seyfeddin Fârûkî",
    tam_ad: "Hazret-i Seyfeddin Fârûkî (kuddise sirruh)",
    lakap: "Seyfeddin-i Serhendî",
    asir: "XVII. Yüzyıl",
    dogum: "~1640", vefat: "1718",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6341, 76.3953],
    biyografi: "Hazret-i Muhammed Mâsum (kuddise sirruh)'un oğlu ve önde gelen halifesidir. Hazret-i İmâm-ı Rabbânî (kuddise sirruh) sülalesinin bu mübarek halkasında ilim ve maneviyat bir arada akmaktadır. Serhend'de medfundur.",
    portre: null
  },
  {
    id: 27,
    ad: "Hazret-i Nur Muhammed Bedâyûnî",
    tam_ad: "Hazret-i Nur Muhammed Bedâyûnî (kuddise sirruh)",
    lakap: "Şeyh Nur Muhammed",
    asir: "XVII–XVIII. Yüzyıl",
    dogum: "~1664", vefat: "1722",
    sehir: "Bedâyûn", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.0384, 79.1305],
    biyografi: "Hindistan'ın Bedâyûn şehrinde yaşamış ve orada medfundur. Silsiledeki mübarek emaneti büyük bir vefayla nakletmiş; halifesi Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh) aracılığıyla bu nurun Delhi'de yeniden parlamasına vesile olmuştur.",
    portre: null
  },
  {
    id: 28,
    ad: "Hazret-i Mirzâ Mazhar Cân-ı Cânân",
    tam_ad: "Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh)",
    lakap: "Cân-ı Cânân",
    asir: "XVIII. Yüzyıl",
    dogum: "1699", vefat: "1781",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6500, 77.2200],
    biyografi: "Delhi'nin en seçkin manevi şahsiyetlerinden biridir. Derin şiir ve irfanıyla ün kazanmış; Nakşibendiyye, Kâdiriyye ve Çiştiyye gibi büyük tarikatları özünde cem etmiştir. Bir suikast sonucu şehit mertebesine erişmiştir. Delhi'de medfundur.",
    portre: null
  },
  {
    id: 29,
    ad: "Hazret-i Abdullah Dehlevî",
    tam_ad: "Hazret-i Abdullah Dehlevî (kuddise sirruh)",
    lakap: "Gulâm Ali Dehlevî",
    asir: "XVIII–XIX. Yüzyıl",
    dogum: "1743", vefat: "1824",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6139, 77.2090],
    biyografi: "Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh)'ın önde gelen halifesidir. Yetiştirdiği değerli halifeler arasında en büyük yeri Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh) tutmaktadır. Onun aracılığıyla Nakşibendiyye Osmanlı coğrafyasına ulaşmıştır. Delhi'de medfundur.",
    portre: null
  },
  {
    id: 30,
    ad: "Hazret-i Hâlid-i Bağdâdî",
    tam_ad: "Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh)",
    lakap: "Mevlânâ Hâlid, Zülcenâheyn",
    asir: "XVIII–XIX. Yüzyıl",
    dogum: "1779", vefat: "1827",
    sehir: "Bağdat (Şam'da vefat)", ulke: "Irak / Suriye", bolge: "Mezopotamya",
    koordinat: [33.3406, 44.4009],
    biyografi: "Nakşibendiyye'nin Hâlidiyye kolunun kurucusu ve silsilenin Osmanlı coğrafyasındaki en büyük temsilcisidir. Kürdistan'da doğmuş, Delhi'de Hazret-i Abdullah Dehlevî (kuddise sirruh)'den en yüksek halifeliği almış; Bağdat ve İstanbul üzerinden bu nurlu silsileyi Anadolu, Rumeli ve bütün Osmanlı topraklarına yaymıştır. Şam'da vefat etmiş ve orada medfundur.",
    portre: null
  }
];
