(()=>{'use strict';
const $=s=>document.querySelector(s),data=window.NORO_COLLECTION?.items||[],feed=$('.feed');
const icons={download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',share:'<path d="M12 16V3m-5 5 5-5 5 5M5 12v9h14v-9"/>',book:'<path d="M12 5v16M12 5C8 2 4 3 2 4v15c3-1 6-1 10 2 4-3 7-3 10-2V4c-2-1-6-2-10 1Z"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>'};
const icon=k=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[k]+'</svg>';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
let format=matchMedia('(max-width:700px)').matches?'dikey':'yatay',group='Hepsi',active=0,list=[],frames=[],observer,scrollFrame,toastTimer,shareFile=null,shareTarget=null;
const motion=()=>matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth';
function selection(){const p=new URLSearchParams(location.search);return{id:p.get('eser')||location.hash.match(/eser-(\d{2})/)?.[1],format:p.get('gorunum')==='telefon'?'dikey':p.get('gorunum')==='bilgisayar'?'yatay':null}}
const initial=selection();if(initial.format)format=initial.format;
function current(){return list[active]}
function shareUrl(item,kind=format){const u=new URL('https://raufenc.com/noroterbiye/duvar-kagitlari/');u.searchParams.set('eser',item.id);u.searchParams.set('gorunum',kind==='dikey'?'telefon':'bilgisayar');return u.href}
function filename(item,kind=format){return 'Noroterbiye-'+item.id+'-'+(kind==='dikey'?'Telefon':'Bilgisayar')+'.png'}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function setUrl(){const item=current();if(!item)return;const u=new URL(location.href);u.searchParams.set('eser',item.id);u.searchParams.set('gorunum',format==='dikey'?'telefon':'bilgisayar');u.hash='';history.replaceState(null,'',u)}
function loadFrame(index,full=false){const card=frames[index],item=list[index];if(!card||!item)return;const img=card.querySelector('.art-image');if(full&&img.dataset.full!==format){img.dataset.full=format;img.src=item[format].src}else if(!img.getAttribute('src'))img.src=item[format].preview;card.querySelector('.art-backdrop').style.backgroundImage='url("'+item[format].preview+'")'}
function activate(index,write=true){if(!list.length)return;active=Math.max(0,Math.min(index,list.length-1));frames.forEach((card,i)=>{card.inert=i!==active;card.setAttribute('aria-current',String(i===active));if(Math.abs(i-active)>2){const img=card.querySelector('.art-image');img.removeAttribute('src');delete img.dataset.full;card.querySelector('.art-backdrop').style.backgroundImage=''}});loadFrame(active,true);loadFrame(active-1);loadFrame(active+1);$('#position').textContent=(active+1)+' / '+list.length;$('#previous').disabled=active===0;$('#next').disabled=active===list.length-1;if(write)setUrl()}
function go(index,behavior=motion()){if(!list[index])return;feed.scrollTo({top:index*feed.clientHeight,behavior});if(behavior==='auto')activate(index)}
function action(kind,label,callback){const button=el('button','action');button.type='button';const disc=el('span','disc');disc.innerHTML=icon(kind);button.append(disc,el('span','',label));button.addEventListener('click',callback);return button}
function render(id){observer?.disconnect();list=data.filter(x=>group==='Hepsi'||x.group===group);feed.replaceChildren();frames=[];feed.scrollTop=0;document.querySelectorAll('[data-format]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.format===format)));
 list.forEach((item,index)=>{const card=el('article','wallpaper');card.dataset.format=format;card.setAttribute('aria-label',item.id+' · '+item.title);card.append(el('div','art-backdrop'));const img=el('img','art-image');img.alt=item.title;img.width=item[format].width;img.height=item[format].height;img.decoding='async';img.addEventListener('error',()=>{if(card.querySelector('.image-error'))return;const error=el('div','image-error','Resim yüklenemedi.');const retry=el('button','','Yeniden dene');retry.type='button';retry.onclick=()=>{error.remove();img.src=item[format].src};error.append(retry);card.append(error)});card.append(img);
 const caption=el('div','caption');caption.append(el('p','eyebrow',item.group),el('h1','',item.title));const trace=el('button','trace');trace.type='button';trace.innerHTML=icon('book');trace.append(el('span','','Kitaptaki izi'));trace.onclick=()=>book(item);caption.append(trace);card.append(caption);
 const actions=el('div','actions');const download=el('a','action');download.href=item[format].src;download.download=filename(item);download.setAttribute('aria-label',item.title+' — '+(format==='dikey'?'telefon':'bilgisayar')+' için indir');const disc=el('span','disc');disc.innerHTML=icon('download');download.append(disc,el('span','','İndir'));actions.append(download,action('share','Paylaş',()=>share(item)),action('expand','Sade gör',()=>plain(item)));card.append(actions);if(index===0)card.append(el('div','swipe-hint','Kaydır, sana iyi geleni seç ↓'));feed.append(card);frames.push(card)});
 const wanted=list.findIndex(x=>x.id===id);active=wanted<0?0:wanted;activate(active);requestAnimationFrame(()=>go(active,'auto'));
 if('IntersectionObserver'in window){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)loadFrame(frames.indexOf(e.target))}),{root:feed,rootMargin:'100% 0px',threshold:0});frames.forEach(x=>observer.observe(x))}
}
function sheet(title,className='sheet-body'){const d=$('#sheet');if(d.open)d.close();$('#sheet-title').textContent=title;const body=$('#sheet-content');body.replaceChildren();body.className=className;d.showModal();return body}
function link(label,href,downloadName){const a=el('a','sheet-link',label);a.href=href;if(downloadName)a.download=downloadName;return a}
function book(item){const body=sheet(item.title);body.append(el('p','',item.question),el('p','source','Nöroterbiye · '+item.chapter+' · 2. baskı, s. '+item.page),link('Kitabın dünyasını keşfet ↗','https://raufenc.com/noroterbiye/kitap-haritasi/'));const options=el('div');options.append(link('Telefon için indir ↓',item.dikey.src,filename(item,'dikey')),link('Bilgisayar için indir ↓',item.yatay.src,filename(item,'yatay')));body.append(options)}
function plain(item){const body=sheet(item.title);const img=el('img');img.src=item[format].src;img.alt=item.title;img.style.cssText='display:block;width:100%;max-height:60dvh;object-fit:contain';body.append(img,link('Orijinali indir ↓',item[format].src,filename(item)));const a=link('Resmi ayrı aç ↗',item[format].src);a.target='_blank';a.rel='noopener';body.append(a)}
function share(item){const body=sheet('Paylaş');const kind=format;shareFile=null;const target={id:item.id,kind};shareTarget=target;body.append(el('p','',item.title));
 const fileButton=el('button','sheet-link primary','Görsel hazırlanıyor…');fileButton.type='button';fileButton.disabled=true;
 const nativeFile=!!(navigator.share&&navigator.canShare&&window.File);if(nativeFile){body.append(fileButton);fetch(item[kind].src).then(r=>{if(!r.ok)throw Error('download');return r.blob()}).then(blob=>{if(shareTarget!==target)return;shareFile=new File([blob],filename(item,kind),{type:'image/png'});if(navigator.canShare({files:[shareFile]})){fileButton.textContent='Görseli gönder';fileButton.disabled=false}else{fileButton.remove();body.append(el('p','share-note','Bu tarayıcıdan bağlantıyı paylaşabilir veya resmi indirip gönderebilirsin.'))}}).catch(()=>{if(shareTarget===target){fileButton.textContent='Görsel hazırlanamadı';body.append(link('Resmi aç veya indir ↓',item[kind].src,filename(item,kind)))}})}
 fileButton.onclick=async()=>{if(!shareFile||shareTarget!==target)return;try{await navigator.share({files:[shareFile],title:item.title+' — NöroTerbiye'});$('#sheet').close()}catch(e){if(e.name!=='AbortError')toast('Paylaşım açılamadı. Resmi indirip gönderebilirsin.')}};
 if(navigator.share){const send=el('button','sheet-link','Bağlantıyı paylaş');send.type='button';send.onclick=async()=>{try{await navigator.share({title:item.title+' — NöroTerbiye',text:'Nöroterbiye’den bir görsel hatırlayış.',url:shareUrl(item,kind)});$('#sheet').close()}catch(e){if(e.name!=='AbortError')toast('Bağlantıyı kopyalayarak paylaşabilirsin.')}};body.append(send)}
 const copy=el('button','sheet-link','Bağlantıyı kopyala');copy.type='button';copy.onclick=async()=>{const url=shareUrl(item,kind);try{if(!navigator.clipboard)throw Error('clipboard');await navigator.clipboard.writeText(url);toast('Bu resmin bağlantısı kopyalandı.')}catch{let field=body.querySelector('input');if(!field){field=el('input','copy-field');field.value=url;field.readOnly=true;field.setAttribute('aria-label','Paylaşılacak bağlantı');body.append(field)}field.focus();field.select();toast('Bağlantıyı seçip kopyalayabilirsin.')}};body.append(copy,link('Resmi indir ↓',item[kind].src,filename(item,kind)),el('p','share-note','Bağlantıyı açan kişi doğrudan bu resmi görür.'));
}
function grid(){const body=sheet('50 görsel hatırlayış','thumbnail-grid');data.forEach(item=>{const b=el('button','thumb');b.type='button';b.setAttribute('aria-current',String(item.id===current()?.id));const img=el('img');img.src=item[format].preview;img.loading='lazy';img.alt=item.title;img.width=item[format].width;img.height=item[format].height;if(format==='yatay')img.style.aspectRatio='16 / 9';b.append(img,el('span','',item.id+' · '+item.title));b.onclick=()=>{$('#sheet').close();group='Hepsi';$('#group-filter').value=group;render(item.id);feed.focus({preventScroll:true})};body.append(b)})}
const groups=[...new Set(data.map(x=>x.group))];groups.forEach(g=>{const o=el('option','',g);o.value=g;$('#group-filter').append(o)});$('#group-filter').onchange=e=>{group=e.target.value;render(current()?.id)};
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{if(format===b.dataset.format)return;const id=current()?.id;format=b.dataset.format;render(id)});
$('#previous').onclick=()=>go(active-1);$('#next').onclick=()=>go(active+1);$('#open-grid').onclick=grid;$('#close-sheet').onclick=()=>$('#sheet').close();$('#sheet').addEventListener('close',()=>{shareTarget=null;shareFile=null});
$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#open-menu').onclick=()=>{const body=sheet('NöroTerbiye','menu-links');const links=[['Ana Sayfa',''],['Duvar Kâğıtları','duvar-kagitlari/'],['Sözlük','sozluk/'],['Testler','testler/'],['Oyunlar','oyunlar/'],['Araçlar','araclar/'],['Kitap Haritası','kitap-haritasi/'],['Kitabı Edin','satin-al/']];links.forEach(([label,path])=>{const a=el('a','',label);a.href='https://raufenc.com/noroterbiye/'+path;if(path==='duvar-kagitlari/')a.setAttribute('aria-current','page');body.append(a)})};
feed.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=null;const i=Math.round(feed.scrollTop/feed.clientHeight);if(i!==active)activate(i)})},{passive:true});
document.addEventListener('keydown',e=>{if($('#sheet').open||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;const next=['ArrowDown','ArrowRight','PageDown'].includes(e.key),prev=['ArrowUp','ArrowLeft','PageUp'].includes(e.key);if(next||prev){e.preventDefault();go(active+(next?1:-1))}});
window.addEventListener('popstate',()=>{const s=selection();if(s.format)format=s.format;group='Hepsi';$('#group-filter').value=group;render(s.id)});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>go(active,'auto'),120)});
if(data.length)render(initial.id);else feed.textContent='Koleksiyon açılamadı. Sayfayı yenileyip tekrar dene.';
})();
