const findings=[
{id:"pesin-hukum",code:"SBAB13.1.SB3",process:"Merak etme ve şüphe duyma",title:"Peşin hükümden kaçınma davranışa dönüşmüyor",kind:"Eylem zayıflaması",currentShort:"Önemini belirtir",requiredShort:"İlk hükmünü askıya alır ve değiştirir",commonRequirement:"Öğrenci, peşin hükümden kaçınarak düşüncesini yeni kanıta açık tutmalıdır.",programEvidence:"Öğrenciden ön yargıyı fark etmesi ve peşin hükümden kaçınmanın önemini belirtmesi isteniyor.",diagnosis:"Bir davranışın önemini söylemek, öğrencinin o davranışı gerçekleştirdiğini kanıtlamaz. Program niyeti anlatıyor; performansı görünür kılmıyor.",recommendation:"Öğrenci; ilk kabulünü, bu kabulü zorlayan karşı kanıtı ve kanıt sonrasında değiştirdiği hükmü aynı çalışma kâğıdında gerekçeleriyle gösterir.",source:"Ortak Metin s.80 · Felsefe Programı s.14–15"},
{id:"suphe-araci",code:"SBAB13.1.SB4",process:"Merak etme ve şüphe duyma",title:"Şüphe açıklanıyor; sınama aracı olarak kullanılmıyor",kind:"Eylem zayıflaması",currentShort:"Şüphenin önemini belirtir",requiredShort:"Şüpheyle iddiayı sınar",commonRequirement:"Şüphe, bir iddia veya tanımı sınamak ve gerektiğinde hükmü iyileştirmek için araç olarak kullanılmalıdır.",programEvidence:"Öğrenciden şüpheyi araç olarak kullanmanın önemini belirtmesi bekleniyor.",diagnosis:"“Önemini belirtmek” bilgi düzeyinde kalır. Ortak Metin ise şüphenin bir düşünme işlemi içinde fiilen kullanılmasını ister.",recommendation:"Öğrenci her felsefe tanımına bir sınama sorusu yöneltir; aldığı cevap sonrasında tanımı korur, değiştirir veya reddeder ve kararını gerekçelendirir.",source:"Ortak Metin s.80 · Felsefe Programı s.15"},
{id:"sonuc-boyutu",code:"SBAB13.2.SB1",process:"Derinlemesine düşünme",title:"Sonuçların değer yönü kayboluyor",kind:"Anlam daralması",currentShort:"Teorik / pratik sonuç",requiredShort:"Olumlu / olumsuz sonuç",commonRequirement:"Düşüncelerin doğurabileceği olumlu ve olumsuz sonuçlar incelenmelidir.",programEvidence:"Öğrenciden felsefi düşüncenin teorik ve pratik sonuçlarını analiz etmesi isteniyor.",diagnosis:"Teorik–pratik, sonucun alanını; olumlu–olumsuz ise olası etkisinin yönünü gösterir. Bunlar birbirinin yerine geçmez.",recommendation:"Öğrenci her düşüncenin teorik ve pratik sonuçlarını; olası olumlu ve olumsuz etkileriyle birlikte ayrı sütunlarda analiz eder.",source:"Ortak Metin s.80 · Felsefe Programı s.15"},
{id:"alternatif-sistem",code:"SBAB13.2.SB4",process:"Derinlemesine düşünme",title:"Felsefe gelenekleri adlandırılıyor fakat analiz edilmiyor",kind:"Eylem zayıflaması",currentShort:"Gelenekleri listeler",requiredShort:"İddia ve çıkarımları analiz eder",commonRequirement:"Alternatif düşünce sistemleri, bunların temel iddiaları ve çıkarımları analiz edilmelidir.",programEvidence:"Farklı felsefe gelenekleri adlandırılıyor ve düşüncenin tek kültüre indirgenemeyeceği vurgulanıyor.",diagnosis:"Çeşitliliği göstermek değerlidir; ancak sistemlerin varsayım, iddia, gerekçe ve sonuç yapılarını çözümlemekle aynı işlem değildir.",recommendation:"Öğrenci en az iki felsefe geleneğini “temel varsayım–ana iddia–gerekçe–çıkarım” şemasıyla karşılaştırır.",source:"Ortak Metin s.80 · Felsefe Programı s.15"},
{id:"mantiksal-temel",code:"KB2.18.SB1",process:"Tartışma",title:"Görüş var; mantıksal temellendirme zorunlu değil",kind:"Eylem zayıflaması",currentShort:"Görüş bildirir",requiredShort:"İddia–gerekçe–kanıt kurar",commonRequirement:"Öğrenci görüşünü mantıksal bir temele oturtmalı; iddia ile gerekçesi arasındaki bağı görünür kılmalıdır.",programEvidence:"Öğrenciler işlevlere ilişkin görüşleri listeler ve görüşlerin tutarlılığını tartışır.",diagnosis:"Görüş bildirme ve tutarlılığı konuşma, her iddianın öncül ve gerekçelerle temellendirildiğini garanti etmez.",recommendation:"Öğrenci her görüşünü “iddia–gerekçe–örnek veya kanıt–sonuç” şablonuyla sunar; gerekçe ile sonuç arasındaki bağı açıklar.",source:"Ortak Metin s.81 · Felsefe Programı s.16"},
{id:"mantik-hatasi",code:"KB2.18.SB2",process:"Tartışma",title:"Üç ayrı mantık denetimi tek kelimeye indirgeniyor",kind:"Anlam daralması",currentShort:"Tutarlılığı tartışır",requiredShort:"Çelişki + tutarsızlık + geçersizliği saptar",commonRequirement:"Mantıksal çelişkiler, tutarsızlıklar ve geçersiz çıkarımlar ayrı ayrı tespit edilmelidir.",programEvidence:"Öğrenciler görüşlerin tutarlılığını tartışıyor.",diagnosis:"Tutarlılık denetimi bulunuyor; fakat çelişki ve geçersiz çıkarım öğrenci tarafından yapılacak ayrı işlemler olarak görünmüyor.",recommendation:"Öğrenci her görüş için “çelişki var mı, tutarsızlık var mı, çıkarım geçerli mi?” kontrolünü ayrı ayrı yapar ve bulgusunu gerekçelendirir.",source:"Ortak Metin s.81 · Felsefe Programı s.16"},
{id:"kb-rolu",code:"KB2.18",process:"Program üst bilgisi",title:"Aynı becerinin programdaki rolü belirsiz kalıyor",kind:"Yapısal belirsizlik",currentShort:"Beceriler arası ilişki",requiredShort:"Çekirdek süreç rolü açık etiketi",commonRequirement:"KB2.18 Tartışma, Ortak Metin’de SBAB13 Felsefi Sorgulama becerisinin bütünleşik çekirdek bileşenidir.",programEvidence:"KB2.18 programda “Beceriler Arası İlişkiler” bölümünde listeleniyor; çekirdek ve destekleyici rol ayrımı ayrıca gösterilmiyor.",diagnosis:"Kodun bulunması tek başına yeterli değildir. Aynı kodun çekirdek süreç mi, destekleyici ilişki mi olduğu belirtilmediğinde izlenebilirlik zayıflar.",recommendation:"Üst bilgide “Alan becerisi: SBAB13”, “Çekirdek bütünleşik beceri: KB2.18”, “Destekleyici beceriler: KB2.5, KB2.7, KB2.10, KB2.13, KB3.3” ayrımı açıkça yazılır.",source:"Ortak Metin s.80–81 · Felsefe Programı s.13–14"}
];

const directMatches=[
["SBAB13.1.SB1","Merak etmek"],["SBAB13.1.SB2","Şüphe ile yaklaşmak"],["SBAB13.2.SB2","Farklı açılardan analiz etmek"],["SBAB13.2.SB3","Açık fikirlilikle değerlendirmek"],["SBAB13.2.SB5","Düşüncesini gerektiğinde değiştirmek"],["SBAB13.3.SB1","Felsefi soru yöneltmek"],["SBAB13.3.SB2","Bütüncül bakmak"],["SBAB13.3.SB3","Refleksif olmak"],["SBAB13.3.SB4","Sokratik yaklaşmak"],["SBAB13.3.SB5","Yığılımlı ilerlemek"],["SBAB13.4.SB1","Eleştiriye açık olmak"],["SBAB13.4.SB2","Güçlü ve zayıf yönleri tespit etmek"],["SBAB13.4.SB3","İrdelemek"],["SBAB13.4.SB4","Değerlendirmek"],["KB2.18.SB3","Çürütmek veya kabul etmek"]
];

const state={query:"",kind:"Tümü",selectedId:findings[0].id,reviewed:[],view:"desk",presenting:false};
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const els={list:$("#finding-list"),result:$("#result-count"),code:$("#detail-code"),process:$("#detail-process"),title:$("#detail-title"),badge:$("#kind-badge"),current:$("#current-short"),required:$("#required-short"),common:$("#common-requirement"),evidence:$("#program-evidence"),diagnosis:$("#diagnosis"),recommendation:$("#recommendation"),source:$("#source"),review:$("#review-button"),reviewCount:$("#review-count"),progress:$("#review-progress"),toast:$("#toast")};

function escapeHtml(value){const node=document.createElement("span");node.textContent=value;return node.innerHTML}
function slug(kind){return kind==="Anlam daralması"?"meaning":kind==="Eylem zayıflaması"?"action":"structure"}
function filtered(){const q=state.query.trim().toLocaleLowerCase("tr");return findings.filter(item=>(state.kind==="Tümü"||item.kind===state.kind)&&(!q||[item.code,item.process,item.title,item.kind,item.diagnosis,item.recommendation].join(" ").toLocaleLowerCase("tr").includes(q)))}
function selected(){const list=filtered();return list.find(item=>item.id===state.selectedId)||list[0]||findings[0]}
function showToast(message){els.toast.textContent=message;els.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.remove("show"),1800)}

function renderList(){const list=filtered();els.result.textContent=`${list.length} bulgu gösteriliyor`;els.list.innerHTML=list.map(item=>{const index=findings.indexOf(item)+1;const reviewed=state.reviewed.includes(item.id);return `<button class="finding-list-item ${selected().id===item.id?"active":""}" data-id="${item.id}" type="button"><span class="finding-index">${String(index).padStart(2,"0")}</span><span class="finding-list-copy"><small>${escapeHtml(item.code)} · ${escapeHtml(item.kind)}</small><strong>${escapeHtml(item.title)}</strong></span>${reviewed?'<span class="review-dot" title="Komisyonca incelendi">✓</span>':'<span class="list-arrow">→</span>'}</button>`}).join("");$$('.finding-list-item').forEach(button=>button.addEventListener("click",()=>{state.selectedId=button.dataset.id;render()}))}

function renderDetail(){const item=selected();state.selectedId=item.id;els.code.textContent=item.code;els.process.textContent=item.process;els.title.textContent=item.title;els.badge.className=`kind-badge ${slug(item.kind)}`;els.badge.textContent=item.kind;els.current.textContent=item.currentShort;els.required.textContent=item.requiredShort;els.common.textContent=item.commonRequirement;els.evidence.textContent=item.programEvidence;els.diagnosis.textContent=item.diagnosis;els.recommendation.textContent=item.recommendation;els.source.textContent=item.source;const done=state.reviewed.includes(item.id);els.review.classList.toggle("reviewed",done);els.review.innerHTML=done?'<span aria-hidden="true">✓</span> İncelendi olarak işaretli':'<span aria-hidden="true">○</span> Komisyonca incelendi'}
function renderProgress(){els.reviewCount.textContent=`${state.reviewed.length} / ${findings.length}`;els.progress.style.width=`${state.reviewed.length/findings.length*100}%`}
function render(){renderList();renderDetail();renderProgress()}

function selectRelative(direction){const list=filtered();if(!list.length)return;const current=Math.max(0,list.findIndex(item=>item.id===selected().id));state.selectedId=list[(current+direction+list.length)%list.length].id;render();if(state.presenting)window.scrollTo({top:0,behavior:"smooth"})}
function toggleReviewed(){const id=selected().id;state.reviewed=state.reviewed.includes(id)?state.reviewed.filter(item=>item!==id):[...state.reviewed,id];localStorage.setItem("tymm-felsefe-reviewed",JSON.stringify(state.reviewed));render();showToast(state.reviewed.includes(id)?"Bulgu incelendi olarak işaretlendi":"İnceleme işareti kaldırıldı")}
function setView(view){state.view=view;$$('.view-tab').forEach(button=>button.classList.toggle("active",button.dataset.view===view));$$('.view-panel').forEach(panel=>panel.classList.remove("active"));$(`#${view}-view`).classList.add("active")}

function renderTable(){const table=$("#compact-table");table.innerHTML='<div class="compact-head"><span>Kod / tür</span><span>Programda olan</span><span>Olması gereken</span><span>Düzeltme</span></div>'+findings.map(item=>`<button class="compact-row" data-id="${item.id}" type="button"><span><b>${escapeHtml(item.code)}</b><small>${escapeHtml(item.kind)}</small></span><span class="wrong">${escapeHtml(item.currentShort)}</span><span class="right">${escapeHtml(item.requiredShort)}</span><span>${escapeHtml(item.recommendation)}</span></button>`).join("");$$('.compact-row').forEach(button=>button.addEventListener("click",()=>{state.selectedId=button.dataset.id;setView("desk");render();$("#workbench").scrollIntoView({behavior:"smooth",block:"start"})}))}
function renderMatches(){$("#matched-grid").innerHTML=directMatches.map(([code,label])=>`<div><i>✓</i><span><b>${escapeHtml(code)}</b>${escapeHtml(label)}</span><small>Doğrudan karşılık</small></div>`).join("")}
function csvEscape(value){return `"${String(value).replaceAll('"','""')}"`}
function downloadCsv(){const headers=["Kod","Süreç","Hata türü","Bulgu","Programdaki ifade","Beklenen","Neden sorun","Önerilen düzeltme","Kaynak"];const rows=findings.map(item=>[item.code,item.process,item.kind,item.title,item.programEvidence,item.commonRequirement,item.diagnosis,item.recommendation,item.source]);const csv="\uFEFF"+[headers,...rows].map(row=>row.map(csvEscape).join(";")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="felsefe-1-tema-bulgu-listesi.csv";link.click();URL.revokeObjectURL(url);showToast("Bulgu tablosu indirildi")}

$("#search-input").addEventListener("input",event=>{state.query=event.target.value;render()});
$$('#kind-filters button').forEach(button=>button.addEventListener("click",()=>{state.kind=button.dataset.kind;$$('#kind-filters button').forEach(item=>item.classList.toggle("active",item===button));render()}));
$$('.view-tab').forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));
$("#previous-button").addEventListener("click",()=>selectRelative(-1));$("#next-button").addEventListener("click",()=>selectRelative(1));els.review.addEventListener("click",toggleReviewed);
$("#copy-button").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(selected().recommendation);$("#copy-button").classList.add("copied");$("#copy-button").textContent="✓ Kopyalandı";setTimeout(()=>{$("#copy-button").classList.remove("copied");$("#copy-button").textContent="▣ Metni kopyala"},1600)}catch{showToast("Metin seçilemedi; düzeltmeyi elle kopyalayabilirsiniz")}});
$("#print-button").addEventListener("click",()=>window.print());$("#csv-button").addEventListener("click",downloadCsv);
$("#presentation-button").addEventListener("click",()=>{state.presenting=!state.presenting;document.body.classList.toggle("is-presenting",state.presenting);$("#presentation-button").classList.toggle("active",state.presenting);$("#presentation-button b").textContent=state.presenting?"Sunumdan çık":"Sunum modu"});
document.addEventListener("keydown",event=>{if(!state.presenting)return;if(event.key==="ArrowRight")selectRelative(1);if(event.key==="ArrowLeft")selectRelative(-1);if(event.key==="Escape")$("#presentation-button").click()});

try{const saved=JSON.parse(localStorage.getItem("tymm-felsefe-reviewed")||"[]");if(Array.isArray(saved))state.reviewed=saved.filter(id=>findings.some(item=>item.id===id))}catch{}
renderTable();renderMatches();render();
